(()=>{'use strict';
const ART=window.DESPERTAR_ART||{},KEY='despertar-online-v100',LEGACY_KEYS=['despertar-v063-save','projeto_despertar_web_v03_pixel','projeto_despertar_web_v03'];
const classes={
Guerreiro:{role:'Linha de frente',stats:{FOR:8,VIT:10,AGI:4,INT:2,DEX:4,SORTE:2},skills:['Corte de Ruptura','Guarda de Ferro','Investida','Brado de Guerra']},
Mago:{role:'Controle arcano',stats:{FOR:2,VIT:5,AGI:4,INT:10,DEX:5,SORTE:3},skills:['Bola de Fogo','Nova Arcana','Passo Etéreo','Barreira']},
Arqueiro:{role:'Precisão e alcance',stats:{FOR:4,VIT:6,AGI:8,INT:3,DEX:10,SORTE:4},skills:['Disparo Rápido','Tiro Preciso','Passo do Caçador','Chuva de Flechas']},
Ladino:{role:'Mobilidade e crítico',stats:{FOR:5,VIT:5,AGI:10,INT:3,DEX:9,SORTE:5},skills:['Ataque Rápido','Golpe pelas Costas','Desaparecer','Dança das Lâminas']}};
const combatKit={
Guerreiro:{
  basic:{name:'Espadada',type:'melee',range:126,mult:1,fx:'sword-slash'},
  q:{name:'Corte de Ruptura',type:'melee',range:180,mult:1.7,cost:10,fx:'sword-wave'},
  e:{name:'Guarda de Ferro',type:'guard',duration:2.2,cost:12,fx:'guard'},
  r:{name:'Investida',type:'dash-hit',distance:185,range:90,mult:1.35,cost:16,fx:'charge'}
},
Mago:{
  basic:{name:'Projétil Arcano',type:'projectile',range:620,mult:.95,speed:560,cost:0,fx:'arcane'},
  q:{name:'Bola de Fogo',type:'projectile',range:700,mult:1.8,speed:430,cost:14,fx:'fireball',splash:95},
  e:{name:'Nova Arcana',type:'aoe',range:185,mult:1.45,cost:18,fx:'arcane-nova'},
  r:{name:'Passo Etéreo',type:'teleport',distance:190,cost:12,fx:'ethereal'}
},
Arqueiro:{
  basic:{name:'Flecha',type:'projectile',range:720,mult:1,speed:720,cost:0,fx:'arrow'},
  q:{name:'Disparo Rápido',type:'multishot',range:700,mult:.72,speed:760,cost:10,shots:3,fx:'arrow'},
  e:{name:'Tiro Preciso',type:'projectile',range:850,mult:2.1,speed:900,cost:16,fx:'piercing-arrow',pierce:true},
  r:{name:'Passo do Caçador',type:'dash',distance:150,cost:9,fx:'hunter-step'}
},
Ladino:{
  basic:{name:'Corte de Adaga',type:'melee',range:108,mult:1.05,fx:'dagger-slash'},
  q:{name:'Ataque Rápido',type:'multi-melee',range:120,mult:.7,hits:3,cost:9,fx:'dagger-flurry'},
  e:{name:'Golpe pelas Costas',type:'backstab',range:260,mult:2.35,cost:16,fx:'shadow-stab'},
  r:{name:'Desaparecer',type:'vanish',duration:1.6,distance:130,cost:14,fx:'vanish'}
}};
const ATTR_KEYS=['FOR','VIT','AGI','INT','DEX','SORTE'];
function generatedAttributes(className){const base={...(classes[className]?.stats||classes.Guerreiro.stats)};for(let i=0;i<4;i++){const k=ATTR_KEYS[Math.floor(Math.random()*ATTR_KEYS.length)];base[k]++}return base}
function ensureAttributes(){if(!state.player.attributes)state.player.attributes={...(classes[state.player.class]?.stats||classes.Guerreiro.stats)};if(!Number.isFinite(state.player.attributePoints))state.player.attributePoints=0;for(const k of ATTR_KEYS)if(!Number.isFinite(state.player.attributes[k]))state.player.attributes[k]=classes[state.player.class]?.stats?.[k]||1}
const professions=[['Ferreiro','Melhora armas, armaduras e reparos.'],['Minerador','Aumenta minério e descoberta de veios.'],['Cozinheiro','Produz refeições e bônus temporários.'],['Alquimista','Cria poções, catalisadores e antídotos.'],['Engenheiro','Constrói máquinas, defesas e geradores.'],['Pesquisador','Analisa portais, monstros e tecnologia.']];
const chapters=[['Capítulo 1','A rua que bebeu o próprio nome','Orla e Cisterna'],['Capítulo 2','O pedágio dos ausentes','Estrada das Lanternas'],['Capítulo 3','O turno que não acabou','Pedreiras de Âmbar'],['Capítulo 4','As raízes que assinam','Jardim Suspenso']];
const defaultState=()=>({version:100,mode:'local',account:{email:'',createdAt:new Date().toISOString()},player:{name:'Desperto',class:'Guerreiro',profession:null,level:1,xp:0,xpNext:100,hp:160,maxHp:160,energy:100,maxEnergy:100,gold:300,cash:0,rank:'—',reputation:0,pvpWins:0,attributes:{FOR:8,VIT:10,AGI:4,INT:2,DEX:4,SORTE:2},attributePoints:0},resources:{madeira:120,pedra:100,ferro:60,comida:100,essencia:0},inventory:[{name:'Carteira de Sobrevivente',qty:1,rarity:'comum'},{name:'Ração de Campo',qty:3,rarity:'comum'}],skills:{points:0,levels:{}},campaign:{chapter:1,mission:'Novos Caminhos',tutorial:'go_guild',completed:[]},missions:{goblin:{accepted:false,kills:0,ready:false,turnedIn:false},daily:[]},guild:{registered:false,clan:null,alliance:null},city:{baseLevel:1,buildings:{Abrigo:1,Depósito:1,Horta:1,Oficina:0}},social:{messages:{global:[],trade:[],clan:[],alliance:[],private:[]}},ui:{page:'city',chat:'global'}});
let selectedRegisterClass='Guerreiro',battle=null,keys=new Set(),raf=0,last=0,state=loadState();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function merge(b,c){if(Array.isArray(b))return Array.isArray(c)?c:b;if(b&&typeof b==='object'){const o={};for(const k of new Set([...Object.keys(b),...Object.keys(c||{})]))o[k]=(k in b)?merge(b[k],c?.[k]):c[k];return o}return c??b}
function migrateLegacy(){for(const k of LEGACY_KEYS){try{const raw=localStorage.getItem(k);if(!raw)continue;const o=JSON.parse(raw),p=o.player||o?.state?.player;if(!p)continue;const n=defaultState();n.player.name=p.name||n.player.name;n.player.class=p.class||p.classId||n.player.class;n.player.class=String(n.player.class).charAt(0).toUpperCase()+String(n.player.class).slice(1).toLowerCase();if(!classes[n.player.class])n.player.class='Guerreiro';n.player.level=p.level||1;n.player.xp=p.xp||0;n.player.gold=p.gold||300;n.player.cash=p.cash||0;n.player.rank=p.rank||'F';n.guild.registered=!!(p.guildRegistered||p.guildCard);n.campaign.tutorial=o.mission||n.campaign.tutorial;if(o.mission==='done')n.campaign.completed.push('tutorial');return n}catch{}}return null}
function loadState(){try{const raw=localStorage.getItem(KEY);if(raw)return merge(defaultState(),JSON.parse(raw))}catch{}const m=migrateLegacy();if(m){localStorage.setItem(KEY,JSON.stringify(m));return m}return defaultState()}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function artSheet(c){return ART.classes?.[c]?.sheet||''}
function spriteFrame(c,d='front'){const i=ART.frames?.[d]??0;return {url:artSheet(c),pos:`${i*100/7}% 0`}}
function spriteStyle(c,d='front'){const f=spriteFrame(c,d);return `background-image:url('${f.url}');background-position:${f.pos}`}
function spriteHtml(c,d='front',extra=''){return `<span class="sprite-frame ${extra}" style="${spriteStyle(c,d)}" aria-label="${esc(c)}"></span>`}
function paintSprite(el,c,d='front'){if(!el)return;const f=spriteFrame(c,d);el.style.backgroundImage=`url('${f.url}')`;el.style.backgroundPosition=f.pos;el.classList.add('sprite-frame')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1800)}
function syncDerived(){ensureAttributes();const a=state.player.attributes;const classBase=state.player.class==='Guerreiro'?90:state.player.class==='Mago'?65:state.player.class==='Arqueiro'?75:70;state.player.maxHp=classBase+a.VIT*7+(state.player.level-1)*6;state.player.hp=Math.min(Math.max(1,state.player.hp||state.player.maxHp),state.player.maxHp);state.player.maxEnergy=70+a.INT*5+a.AGI*2+(state.player.class==='Mago'?35:0);state.player.energy=Math.min(Math.max(0,state.player.energy??state.player.maxEnergy),state.player.maxEnergy)}
function combatPower(){ensureAttributes();const a=state.player.attributes,l=state.player.level;switch(state.player.class){case'Mago':return 8+a.INT*1.8+a.DEX*.25+l*1.8;case'Arqueiro':return 8+a.DEX*1.55+a.AGI*.5+l*1.8;case'Ladino':return 8+a.DEX*1.2+a.AGI*.85+l*1.8;default:return 8+a.FOR*1.65+a.DEX*.3+l*1.8}}
function critChance(){ensureAttributes();const a=state.player.attributes;return Math.min(45,3+a.SORTE*.7+(state.player.class==='Ladino'?5:state.player.class==='Arqueiro'?2:0))}
function rollDamage(mult=1){const crit=Math.random()*100<critChance();return {value:Math.max(1,Math.round(combatPower()*mult*(crit?1.65:1))),crit}}
function skillLevelMultiplier(name){const lv=state.skills.levels[name]||1;return 1+(lv-1)*.08}
function renderHud(){syncDerived();$('#hudName').textContent=state.player.name;$('#hudClass').textContent=`${state.player.class} • Nv.${state.player.level}`;paintSprite($('#playerPortrait'),state.player.class,'front');$('#hpBar').style.width=`${100*state.player.hp/state.player.maxHp}%`;$('#energyBar').style.width=`${100*state.player.energy/state.player.maxEnergy}%`;$('#hpText').textContent=`${state.player.hp}/${state.player.maxHp}`;$('#energyText').textContent=`${state.player.energy}/${state.player.maxEnergy}`;$('#goldValue').textContent=state.player.gold.toLocaleString('pt-BR');$('#cashValue').textContent=state.player.cash;$('#rankValue').textContent=state.player.rank}
function addChat(ch,name,text,system=false){const a=state.social.messages[ch]||(state.social.messages[ch]=[]);a.push({t:new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),name,text,system});if(a.length>60)a.splice(0,a.length-60);save();if(state.ui.chat===ch)renderChat()}
function seedChat(){if(state.social.messages.global.length)return;addChat('global','Sistema','Você entrou em Esperança.',true);addChat('global','Mirela','A Guilda abriu novas missões Rank F.');addChat('trade','Breno','Compro ferro e madeira. Procure a Oficina.')}
function renderChat(){const ch=state.ui.chat;$$('[data-chat]').forEach(b=>b.classList.toggle('active',b.dataset.chat===ch));const log=$('#chatLog');log.innerHTML=(state.social.messages[ch]||[]).map(m=>`<div class="chat-line ${m.system?'system':''}"><span class="time">[${esc(m.t)}]</span> <span class="name">${esc(m.name)}:</span> ${esc(m.text)}</div>`).join('');log.scrollTop=log.scrollHeight}
function renderOnline(){const ps=[state.player.name,'Mirela Santos','Caio Nunes','Davi Moura','Breno Carvalho'];$('#onlinePlayers').innerHTML=ps.map((n,i)=>`<div class="online-player"><span>${esc(n)}</span><span>${i?['Nv.4','Nv.2','Nv.6','Nv.8'][i-1]:`Nv.${state.player.level}`}</span></div>`).join('')}
function showGame(){seedChat();$('#authScreen').classList.add('hidden');$('#gameShell').classList.remove('hidden');renderHud();renderOnline();renderChat();go(state.ui.page||'city')}
function authTab(tab){$$('[data-auth-tab]').forEach(b=>b.classList.toggle('active',b.dataset.authTab===tab));$$('.auth-form').forEach(f=>f.classList.toggle('active',f.id===(tab==='login'?'loginForm':'registerForm')))}
function renderClassPicks(){const e=$('#classPicks');e.innerHTML=Object.keys(classes).map(c=>`<button type="button" class="class-pick ${c===selectedRegisterClass?'active':''}" data-reg-class="${c}">${spriteHtml(c,'front','class-pick-sprite')}<b>${c}</b></button>`).join('');$$('[data-reg-class]').forEach(b=>b.onclick=()=>{selectedRegisterClass=b.dataset.regClass;renderClassPicks()})}
function go(p){state.ui.page=p;save();$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));$('#sideNav').classList.remove('open');stopBattle();const s=$('#mainStage');s.innerHTML='';(pages[p]||pages.city)(s);$('#footerLocation').textContent=({city:'Esperança',character:'Personagem',inventory:'Inventário',skills:'Habilidades',missions:'Missões',work:'Trabalhos',hunt:'Caçadas',map:'Mapa do Mundo',guild:'Guilda',ranking:'Ranking',social:'Social',settings:'Configurações'})[p]||'Esperança';s.focus({preventScroll:true})}
function hero(s,bg,title,sub,body,acts=''){s.innerHTML=`<section class="page"><div class="hero-scene" style="background-image:url('${bg}')"><div class="scene-copy"><div class="eyebrow">${sub}</div><h2>${title}</h2><p>${body}</p><div class="action-row">${acts}</div></div></div><div id="pageBelow"></div></section>`}
const btn=(label,a,primary=false)=>`<button class="action-btn ${primary?'primary':''}" data-action="${a}">${label}</button>`;
function bindActions(root=document){root.querySelectorAll('[data-action]').forEach(b=>{b.type='button';b.onclick=e=>{e.preventDefault();e.stopPropagation();const fn=actions[b.dataset.action];if(fn)fn(b);else toast('Ação indisponível nesta versão.')}})}
function gainXp(n){state.player.xp+=n;while(state.player.xp>=state.player.xpNext){state.player.xp-=state.player.xpNext;state.player.level++;state.player.xpNext=Math.round(state.player.xpNext*1.25);state.skills.points++;state.player.attributePoints=(state.player.attributePoints||0)+5;toast(`Nível ${state.player.level}! +5 atributos • +1 habilidade`)}syncDerived();save()}
const actions={guild:()=>go('guild'),missions:()=>go('missions'),hunt:()=>go('hunt'),work:()=>go('work'),map:()=>go('map'),base:()=>openBase(),
acceptGoblin:()=>{state.missions.goblin.accepted=true;state.campaign.mission='Infestação de Goblins';save();toast('Missão aceita. Portal Rank F liberado.');go('hunt')},
startGoblin:()=>startBattle(),
registerGuild:()=>{state.guild.registered=true;state.player.rank='F';state.player.gold+=25;save();renderHud();toast('Registro concluído. Rank F obtido.');go('guild')},
turnGoblin:()=>{const q=state.missions.goblin;if(!q.ready||q.turnedIn)return;q.turnedIn=true;state.player.gold+=80;gainXp(100);state.campaign.mission='Fale com o Capitão Raul';save();renderHud();toast('+80 Ouro • +100 EXP');go('guild')},
talkRaul:()=>modal('Capitão Raul','Você completou sua primeira incursão oficial. A partir daqui, a Guilda acompanha seu progresso, reputação e acesso a Portais.'),
gatherWood:()=>{state.resources.madeira+=20;state.player.energy=Math.max(0,state.player.energy-5);save();renderHud();toast('+20 Madeira')},
gatherOre:()=>{state.resources.ferro+=8;state.player.energy=Math.max(0,state.player.energy-7);save();renderHud();toast('+8 Ferro')},
jobPatrol:()=>{state.player.gold+=18;gainXp(8);save();renderHud();toast('+18 Ouro • +8 EXP')},
jobDepot:()=>{state.resources.comida+=12;state.player.gold+=12;save();renderHud();toast('+12 Comida • +12 Ouro')},
upgradeBase:()=>{const c=100*state.city.baseLevel;if(state.player.gold<c)return toast(`Precisa de ${c} Ouro`);state.player.gold-=c;state.city.baseLevel++;save();renderHud();toast(`Base evoluiu para nível ${state.city.baseLevel}`);openBase()},
logout:()=>{save();$('#gameShell').classList.add('hidden');$('#authScreen').classList.remove('hidden')},noop:()=>{save();toast('Progresso salvo.')}};
const pages={
city(s){hero(s,ART.scenes?.city||'','Esperança','Cidade inicial • Último Refúgio','Uma cidade fortificada entre ruínas. Aqui os Despertos treinam, negociam, trabalham, formam grupos e recebem contratos da Guilda.',btn('Entrar na Guilda','guild',true)+btn('Quadro de Missões','missions')+btn('Trabalhos da Cidade','work')+btn('Mapa','map'));const b=$('#pageBelow');b.innerHTML=`<div class="dashboard-grid"><div class="card gold"><h3>Objetivo atual</h3><p><strong>${esc(state.campaign.mission)}</strong></p><p>${state.missions.goblin.ready&&!state.missions.goblin.turnedIn?'Retorne à Guilda e entregue o relatório para Elena.':'Acompanhe a campanha e os contratos do quadro.'}</p></div><div class="card"><h3>Base pessoal</h3><div class="big-stat">Nv.${state.city.baseLevel}</div><p>Abrigo, depósito, horta e oficina evoluem separadamente.</p>${btn('Administrar','base')}</div><div class="card"><h3>Economia</h3><p>Madeira: <strong>${state.resources.madeira}</strong><br>Ferro: <strong>${state.resources.ferro}</strong><br>Comida: <strong>${state.resources.comida}</strong></p></div><div class="card"><h3>Guilda</h3><p>${state.guild.registered?'Registro ativo • Rank '+state.player.rank:'Você ainda não concluiu o registro oficial.'}</p>${btn('Abrir Guilda','guild')}</div><div class="card"><h3>Caçada Rank F</h3><p>Infestação de Goblins • ${state.missions.goblin.kills}/5</p>${btn(state.missions.goblin.accepted?'Ir ao Portal':'Ver contrato',state.missions.goblin.accepted?'hunt':'missions')}</div><div class="card"><h3>Servidor</h3><p>Interface online pronta para contas, chat compartilhado, ranking e PvP. Nesta build os dados ainda ficam locais.</p></div></div>`;bindActions(s)},
character(s){ensureAttributes();syncDerived();const c=classes[state.player.class],a=state.player.attributes;s.innerHTML=`<section class="page"><div class="split"><div class="card portrait-card gold">${spriteHtml(state.player.class,'front','character-portrait-sprite')}<div><div class="eyebrow">DESPERTO</div><h2>${esc(state.player.name)}</h2><p>${state.player.class} • ${c.role}</p><p>Nível <strong>${state.player.level}</strong> • Rank <strong>${state.player.rank}</strong></p><div class="progress"><i style="width:${Math.min(100,100*state.player.xp/state.player.xpNext)}%"></i></div><p>EXP ${state.player.xp}/${state.player.xpNext}</p></div></div><div class="card"><h3>Atributos</h3><p>Pontos para distribuir: <strong class="attr-points">${state.player.attributePoints||0}</strong></p><div class="stats-table">${ATTR_KEYS.map(k=>`<div class="stat attr-stat"><b>${a[k]}</b><small>${k}</small><button type="button" data-add-attr="${k}" ${state.player.attributePoints<=0?'disabled':''}>+</button></div>`).join('')}</div><p class="muted-help">Cada nível concede 5 pontos de atributos. Eles ficam salvos no personagem.</p></div></div><div class="dashboard-grid"><div class="card"><h3>Combate derivado</h3><p>HP <strong>${state.player.maxHp}</strong><br>Energia <strong>${state.player.maxEnergy}</strong><br>Poder <strong>${Math.round(combatPower())}</strong><br>Crítico <strong>${critChance().toFixed(1)}%</strong></p></div><div class="card"><h3>Profissão</h3><p>${state.player.profession||'Nenhuma profissão escolhida.'}</p></div><div class="card"><h3>Reputação</h3><div class="big-stat">${state.player.reputation}</div></div><div class="card"><h3>PvP</h3><div class="big-stat">${state.player.pvpWins}</div></div></div></section>`;s.querySelectorAll('[data-add-attr]').forEach(b=>b.onclick=()=>{if((state.player.attributePoints||0)<=0)return toast('Sem pontos de atributos.');const k=b.dataset.addAttr;if(!ATTR_KEYS.includes(k))return;state.player.attributes[k]++;state.player.attributePoints--;syncDerived();save();renderHud();go('character')})},inventory(s){s.innerHTML=`<section class="page"><div class="card"><div class="panel-title">Inventário</div><div class="item-list">${state.inventory.map(it=>`<div class="item"><div class="item-top"><b>${esc(it.name)}</b><span class="tag">${esc(it.rarity||'comum')}</span></div><p>Quantidade: ${it.qty||1}</p></div>`).join('')}</div></div><div class="dashboard-grid"><div class="card"><h3>Materiais</h3><p>Madeira <strong>${state.resources.madeira}</strong><br>Pedra <strong>${state.resources.pedra}</strong><br>Ferro <strong>${state.resources.ferro}</strong><br>Comida <strong>${state.resources.comida}</strong><br>Essência <strong>${state.resources.essencia}</strong></p></div><div class="card"><h3>Equipamentos</h3><div class="slot-grid"><div class="slot">Arma</div><div class="slot">Armadura</div><div class="slot">Acessório</div><div class="slot">Relíquia</div></div></div></div></section>`},
skills(s){const c=classes[state.player.class];s.innerHTML=`<section class="page"><div class="card gold"><h3>Habilidades • ${state.player.class}</h3><p>Pontos disponíveis: <strong>${state.skills.points}</strong></p><div class="skill-list">${c.skills.map((x,i)=>`<div class="skill"><div class="item-top"><b>${x}</b><span class="tag">Nv.${state.skills.levels[x]||1}</span></div><p>${['Habilidade ofensiva principal.','Golpe de alto impacto.','Mobilidade ou defesa contextual.','Técnica avançada.'][i]}</p><button class="action-btn" data-up-skill="${x}">Evoluir</button></div>`).join('')}</div></div></section>`;s.querySelectorAll('[data-up-skill]').forEach(b=>b.onclick=()=>{if(state.skills.points<=0)return toast('Sem pontos de habilidade.');const x=b.dataset.upSkill;state.skills.points--;state.skills.levels[x]=(state.skills.levels[x]||1)+1;save();go('skills')})},
missions(s){const q=state.missions.goblin;s.innerHTML=`<section class="page"><div class="card"><div class="panel-title">Quadro de Missões</div><div class="quest-list"><div class="quest ${q.ready?'complete':'active'}"><div class="quest-top"><b>Rank F — Infestação de Goblins</b><span class="tag gold">Principal</span></div><p>Elimine 5 Goblins na primeira incursão oficial.</p><div class="progress"><i style="width:${20*q.kills}%"></i></div><p>${q.kills}/5 • Recompensa: 80 Ouro + 100 EXP</p>${!q.accepted?btn('Aceitar missão','acceptGoblin',true):q.ready&&!q.turnedIn?'<p><strong>Objetivo cumprido. Entregue para Elena na Guilda.</strong></p>':q.turnedIn?'<p>✓ Concluída</p>':btn('Ir para Caçadas','hunt')}</div>${chapters.map((c,i)=>`<div class="quest ${state.campaign.chapter>i+1?'complete':''}"><div class="quest-top"><b>${c[0]} — ${c[1]}</b><span class="tag">Campanha</span></div><p>${c[2]}</p></div>`).join('')}</div></div></section>`;bindActions(s)},
work(s){s.innerHTML=`<section class="page"><div class="card gold"><h3>Trabalhos de Esperança</h3><p>Atividades civis geram recursos e renda sem substituir sua classe de combate.</p></div><div class="dashboard-grid">${[['Patrulhar Muralha','18 Ouro • 8 EXP','jobPatrol'],['Ajudar no Depósito','12 Ouro • 12 Comida','jobDepot'],['Cortar Madeira','20 Madeira','gatherWood'],['Extrair Ferro','8 Ferro','gatherOre']].map(x=>`<div class="card"><h3>${x[0]}</h3><p>${x[1]}</p>${btn('Executar',x[2])}</div>`).join('')}</div><div class="card"><h3>Profissões disponíveis</h3><div class="dashboard-grid">${professions.map(([n,d])=>`<div class="card"><b>${n}</b><p>${d}</p><button class="action-btn" data-prof="${n}">${state.player.profession===n?'Selecionada':'Escolher'}</button></div>`).join('')}</div></div></section>`;bindActions(s);s.querySelectorAll('[data-prof]').forEach(b=>b.onclick=()=>{state.player.profession=b.dataset.prof;save();toast(`Profissão: ${b.dataset.prof}`);go('work')})},
hunt(s){const q=state.missions.goblin;s.innerHTML=`<section class="page"><div class="card gold"><h3>Portais e Caçadas</h3><p>Combates de ação acontecem em instâncias laterais. Cidade, Guilda e administração permanecem no modelo de navegador.</p></div><div class="dashboard-grid"><div class="card"><h3>Portal Rank F</h3><p>Acampamento Goblin</p><p>Progresso: ${q.kills}/5</p>${q.accepted&&!q.ready?btn('Entrar na instância','startGoblin',true):q.ready?'<p><strong>Concluída. Volte à Guilda.</strong></p>':'<p>Aceite a missão no Quadro.</p>'}</div><div class="card"><h3>Ruínas Externas</h3><p>Contrato de patrulha • bloqueado pelo progresso.</p></div><div class="card"><h3>Fenda Instável</h3><p>Eventos dinâmicos futuros.</p></div></div></section>`;bindActions(s)},
map(s){s.innerHTML=`<section class="page"><div class="card gold"><h3>Mapa do Mundo</h3><p>Regiões são desbloqueadas por campanha, nível, reputação e Portais.</p></div><div class="map-grid"><div class="region"><span class="level">Nv.1–10</span><h3>Esperança</h3><p>Último Refúgio. Cidade, Guilda, comércio, base e trabalhos.</p></div><div class="region"><span class="level">Nv.1–5</span><h3>Acampamento Goblin</h3><p>Primeira instância Rank F.</p></div><div class="region locked"><span class="level">Nv.10+</span><h3>Floresta Cinzenta</h3><p>Território mutado.</p></div><div class="region locked"><span class="level">Portal</span><h3>Outros Mundos</h3><p>Reinos e instâncias futuras.</p></div></div></section>`},
guild(s){hero(s,ART.scenes?.guild||'','Guilda dos Aventureiros','Esperança • Distrito Central',state.guild.registered?'Seu registro está ativo. Elena cuida dos relatórios e Raul coordena incursões.':'Elena pode concluir seu registro Rank F e liberar o fluxo oficial de missões.',!state.guild.registered?btn('Registrar com Elena','registerGuild',true):(state.missions.goblin.ready&&!state.missions.goblin.turnedIn?btn('Entregar relatório para Elena','turnGoblin',true):btn('Falar com Capitão Raul','talkRaul'))+btn('Quadro de Missões','missions'));$('#pageBelow').innerHTML=`<div class="dashboard-grid"><div class="card"><div class="npc-profile"><img src="${ART.portraits?.elena||''}" alt="Elena Duarte"><div><h3>Elena Duarte</h3><p>Recepção, registros, relatórios e recompensas.</p></div></div></div><div class="card"><h3>Raul Vilar</h3><p>Capitão de Incursões. Coordena Portais e contratos de campo.</p></div><div class="card"><h3>Clãs</h3><p>${state.guild.clan?'Clã: '+esc(state.guild.clan):'Nenhum clã. O sistema online permitirá criação e convites.'}</p></div></div>`;bindActions(s)},
ranking(s){const rows=[[state.player.name,state.player.level,state.player.gold,state.player.pvpWins],['Mirela Santos',8,1240,3],['Davi Moura',6,980,1],['Caio Nunes',4,740,0],['Breno Carvalho',8,2100,0]].sort((a,b)=>b[1]-a[1]);s.innerHTML=`<section class="page"><div class="card gold"><h3>Ranking de Esperança</h3><p>Na build local, rivais são simulados. O backend online substituirá esta lista por dados reais do servidor.</p></div><div class="card rank-list">${rows.map((r,i)=>`<div class="rank-row"><span><b>#${i+1}</b> ${esc(r[0])}</span><span>Nv.${r[1]} • ${r[2]} Ouro • ${r[3]} PvP</span></div>`).join('')}</div></section>`},
social(s){s.innerHTML=`<section class="page"><div class="dashboard-grid"><div class="card"><h3>Clã</h3><p>Criação, membros, cargos e chat dedicado.</p></div><div class="card"><h3>Aliança</h3><p>Vínculo entre clãs para eventos e territórios.</p></div><div class="card"><h3>Mensagens privadas</h3><p>Conversas entre jogadores.</p></div><div class="card"><h3>Arena</h3><p>PvP e temporadas serão server-authoritative.</p></div><div class="card"><h3>Mercado</h3><p>Itens fabricados por jogadores com origem e atributos rastreáveis.</p></div><div class="card"><h3>Conselho da Cidade</h3><p>Títulos sociais e destaques do servidor.</p></div></div></section>`},
settings(s){s.innerHTML=`<section class="page"><div class="card gold"><h3>Configurações</h3><p>Versão 1.0.2 — correção visual, controles, mobs e interação.</p>${btn('Salvar agora','noop')} ${btn('Sair para login','logout')}</div><div class="card"><h3>Conexão</h3><p><strong>Modo atual:</strong> persistência local.</p><p>Para contas reais, chat compartilhado, ranking global, clãs e PvP persistente, conectaremos um backend Supabase exclusivo do Despertar.</p></div><div class="card"><h3>Controles de combate</h3><p><strong>A</strong> esquerda • <strong>D</strong> direita • <strong>W</strong> pular • <strong>S</strong> agachar • <strong>Shift</strong> esquiva • <strong>Q/E/R</strong> habilidades • <strong>F</strong> interagir • <strong>Espaço</strong> ataque.</p></div></section>`;bindActions(s)}};
function openBase(){modal('Base Pessoal',`<div class="dashboard-grid"><div class="card"><h3>Nível ${state.city.baseLevel}</h3><p>Abrigo ${state.city.buildings.Abrigo}<br>Depósito ${state.city.buildings.Depósito}<br>Horta ${state.city.buildings.Horta}<br>Oficina ${state.city.buildings.Oficina}</p></div><div class="card"><h3>Recursos</h3><p>Madeira ${state.resources.madeira}<br>Pedra ${state.resources.pedra}<br>Ferro ${state.resources.ferro}</p></div></div><button class="action-btn primary" id="upgradeBaseBtn">Melhorar Base (${100*state.city.baseLevel} Ouro)</button>`,()=>$('#upgradeBaseBtn')?.addEventListener('click',actions.upgradeBase))}
function modal(title,body,after){const r=$('#modalRoot');r.innerHTML=`<div class="modal"><h2>${title}</h2><div>${body}</div><div class="modal-actions"><button class="action-btn" data-close-modal>Fechar</button></div></div>`;r.classList.remove('hidden');r.querySelector('[data-close-modal]').onclick=()=>r.classList.add('hidden');after?.()}
function currentKit(){return combatKit[state.player.class]||combatKit.Guerreiro}
function slotSkillName(slot){const arr=classes[state.player.class]?.skills||[];return slot==='q'?arr[0]:slot==='e'?arr[1]:slot==='r'?arr[2]:currentKit().basic.name}
function cooldownFor(slot){if(slot==='basic')return state.player.class==='Ladino' ? .22 : state.player.class==='Arqueiro' ? .34 : state.player.class==='Mago' ? .38 : .36;return slot==='q'?1.2:slot==='e'?2.2:2.6}
function spendEnergy(cost){cost=Math.max(0,cost||0);if(state.player.energy<cost){toast('Energia insuficiente.');return false}state.player.energy=Math.max(0,state.player.energy-cost);renderHud();return true}
function skillDamage(def,slot){const levelMult=slot==='basic'?1:skillLevelMultiplier(slotSkillName(slot));const rolled=rollDamage((def.mult||1)*levelMult);return rolled}
function startBattle(){if(!state.missions.goblin.accepted)return toast('Aceite a missão primeiro.');syncDerived();state.ui.page='hunt';save();battle={x:120,y:0,vy:0,facing:1,crouch:false,jump:false,cameraX:0,portalX:1190,worldW:1280,cooldowns:{basic:0,q:0,e:0,r:0},dodgeCd:0,shieldT:0,invulnT:0,attackAnimT:0,attackAnimKind:'',projectileId:0,projectiles:[],enemies:Array.from({length:5},(_,i)=>({x:440+i*160,hp:34,maxHp:34,dead:i<state.missions.goblin.kills,cd:.45+i*.08,hitT:0,attackT:0,moving:false,facing:-1}))};renderBattle();last=performance.now();raf=requestAnimationFrame(loopBattle)}
function renderBattle(){const s=$('#mainStage'),kit=currentKit(),bg=ART.scenes?.battle||ART.scenes?.city||'';s.innerHTML=`<section class="battle-page"><div class="battle-hud"><span><b>Rank F — Infestação de Goblins</b> • <span id="battleProgress">${state.missions.goblin.kills}/5</span></span><span class="battle-class-label">${state.player.class}</span><button type="button" class="action-btn" id="leaveBattle">Sair da instância</button></div><div class="battle-world" id="battleViewport"><div class="battle-scene" id="battleScene" style="width:${battle.worldW}px;background-image:url('${bg}')"><div class="ground"></div><div id="effectLayer" class="effect-layer"></div><div id="projectileLayer" class="projectile-layer"></div><div id="battlePlayer" class="battle-character sprite-frame" style="${spriteStyle(state.player.class,'right')}" aria-label="${state.player.class}"></div><div id="enemyLayer"></div><div id="portalExit" class="portal-exit hidden" style="left:${battle.portalX}px;background-image:url('${ART.portal||''}')"></div></div><div class="battle-hotbar"><button type="button" data-battle="attack"><b>ESPAÇO</b><span>${kit.basic.name}</span></button><button type="button" data-battle="q"><b>Q</b><span>${kit.q.name}</span></button><button type="button" data-battle="e"><b>E</b><span>${kit.e.name}</span></button><button type="button" data-battle="r"><b>R</b><span>${kit.r.name}</span></button><button type="button" data-battle="f"><b>F</b><span>Interagir</span></button></div><div class="battle-mobile-controls"><button type="button" data-move="KeyA">◀</button><button type="button" data-move="KeyS">▼</button><button type="button" data-move="KeyW">▲</button><button type="button" data-move="KeyD">▶</button></div><div class="battle-tip">A/D mover • W pular • S agachar • Shift esquiva • Espaço ataque básico • Q/E/R habilidades • F portal</div></div></section>`;$('#leaveBattle').onclick=()=>{stopBattle();go('hunt')};document.querySelectorAll('[data-battle]').forEach(b=>b.onclick=()=>battleAction(b.dataset.battle));document.querySelectorAll('[data-move]').forEach(b=>{const code=b.dataset.move;b.onpointerdown=e=>{e.preventDefault();if(code==='KeyW')battleAction('jump');else keys.add(code)};const up=e=>{e.preventDefault();keys.delete(code)};b.onpointerup=up;b.onpointercancel=up;b.onpointerleave=up});renderEnemies()}
function goblinFrame(e){const f=ART.mobs?.goblin?.frames||{};if(e.dead)return f.dead??5;if(e.hitT>0)return f.hit??4;if(e.attackT>0)return f.attack??3;if(e.moving)return(Math.floor(performance.now()/170)%2)?(f.walk1??1):(f.walk2??2);return f.idle??0}
function goblinPos(frame){return `${frame*20}% 0`}
function renderEnemies(){if(!battle)return;const l=$('#enemyLayer');if(!l)return;const sheet=ART.mobs?.goblin?.sheet||'';l.innerHTML=battle.enemies.map((e,i)=>`<div class="enemy ${e.dead?'dead':''}" data-enemy-index="${i}" style="left:${e.x}px"><div class="goblin-sprite" style="background-image:url('${sheet}');background-position:${goblinPos(goblinFrame(e))}"></div><div class="enemy-hp"><i style="width:${100*e.hp/e.maxHp}%"></i></div></div>`).join('');const prog=$('#battleProgress');if(prog)prog.textContent=`${battle.enemies.filter(e=>e.dead).length}/5`;const portal=$('#portalExit');if(portal)portal.classList.toggle('hidden',battle.enemies.some(e=>!e.dead))}
function syncEnemyDom(i,e){const el=document.querySelector(`[data-enemy-index="${i}"]`);if(!el)return;el.style.left=`${e.x}px`;el.classList.toggle('dead',e.dead);const sp=el.querySelector('.goblin-sprite');if(sp){sp.style.backgroundPosition=goblinPos(goblinFrame(e));sp.style.transform=`scaleX(${e.facing<0?-1:1})`}const hp=el.querySelector('.enemy-hp i');if(hp)hp.style.width=`${Math.max(0,100*e.hp/e.maxHp)}%`}
function spawnFx(kind,x=battle.x+44*battle.facing,y=155+battle.y,facing=battle.facing){const layer=$('#effectLayer');if(!layer||!battle)return;const e=document.createElement('div');e.className=`combat-fx fx-${kind}`;e.style.left=`${x}px`;e.style.bottom=`${Math.max(102,y)}px`;e.style.setProperty('--face',facing);layer.appendChild(e);setTimeout(()=>e.remove(),520)}
function damageNumber(x,value,crit=false){const layer=$('#effectLayer');if(!layer)return;const e=document.createElement('div');e.className=`damage-number ${crit?'crit':''}`;e.style.left=`${x}px`;e.style.bottom='185px';e.textContent=`${crit?'CRIT ':''}-${value}`;layer.appendChild(e);setTimeout(()=>e.remove(),650)}
function damageEnemy(i,rolled){const e=battle?.enemies?.[i];if(!e||e.dead)return false;e.hp-=rolled.value;e.hitT=.2;damageNumber(e.x+20,rolled.value,rolled.crit);if(e.hp<=0){e.dead=true;e.hp=0;e.moving=false;state.missions.goblin.kills=battle.enemies.filter(x=>x.dead).length;if(state.missions.goblin.kills>=5){state.missions.goblin.ready=true;const portal=$('#portalExit');if(portal)portal.classList.remove('hidden');toast('Todos os Goblins derrotados. Vá até o portal.')}else toast('Goblin derrotado');save()}syncEnemyDom(i,e);return true}
function targetsInRange(range,{front=true,limit=99}={}){const found=[];for(let i=0;i<battle.enemies.length;i++){const e=battle.enemies[i];if(e.dead)continue;const dx=e.x-battle.x,dist=Math.abs(dx);if(dist<=range&&(!front||Math.sign(dx)===battle.facing||dist<42))found.push({i,e,dist,dx})}found.sort((a,b)=>a.dist-b.dist);return found.slice(0,limit)}
function projectileElement(p){const layer=$('#projectileLayer');if(!layer)return null;const e=document.createElement('div');e.className=`combat-projectile projectile-${p.kind}`;e.dataset.projectileId=p.id;e.style.left=`${p.x}px`;e.style.bottom=`${p.y}px`;e.style.setProperty('--face',p.facing);layer.appendChild(e);return e}
function spawnProjectile(def,rolled,{yOffset=0,damageScale=1}={}){if(!battle)return;const p={id:++battle.projectileId,kind:def.fx||'arcane',x:battle.x+52*battle.facing,y:142+battle.y+yOffset,vx:(def.speed||560)*battle.facing,remaining:def.range||650,damage:{value:Math.max(1,Math.round(rolled.value*damageScale)),crit:rolled.crit},pierce:!!def.pierce,splash:def.splash||0,hit:new Set()};battle.projectiles.push(p);projectileElement(p);spawnFx(p.kind,battle.x+44*battle.facing,142+battle.y,battle.facing)}
function removeProjectile(p){const idx=battle.projectiles.indexOf(p);if(idx>=0)battle.projectiles.splice(idx,1);document.querySelector(`[data-projectile-id="${p.id}"]`)?.remove()}
function updateProjectiles(dt){if(!battle)return;for(const p of [...battle.projectiles]){const dx=p.vx*dt;p.x+=dx;p.remaining-=Math.abs(dx);const el=document.querySelector(`[data-projectile-id="${p.id}"]`);if(el){el.style.left=`${p.x}px`;el.style.bottom=`${p.y}px`}let hitAny=false;for(let i=0;i<battle.enemies.length;i++){const e=battle.enemies[i];if(e.dead||p.hit.has(i))continue;if(Math.abs(e.x-p.x)<38){p.hit.add(i);damageEnemy(i,p.damage);hitAny=true;if(p.splash){spawnFx('explosion',e.x+18,150,1);for(let j=0;j<battle.enemies.length;j++){if(j===i||battle.enemies[j].dead)continue;if(Math.abs(battle.enemies[j].x-e.x)<=p.splash)damageEnemy(j,{value:Math.max(1,Math.round(p.damage.value*.55)),crit:false})}}if(!p.pierce)break}}if((hitAny&&!p.pierce)||p.remaining<=0||p.x<0||p.x>battle.worldW)removeProjectile(p)}}
function playAttackPose(kind){battle.attackAnimT=.28;battle.attackAnimKind=kind}
function basicAttack(){const def=currentKit().basic;if((battle.cooldowns.basic||0)>0)return;const mageBasic=state.player.class==='Mago'&&Math.random()<.5?1:0;if(!spendEnergy((def.cost||0)+mageBasic))return;battle.cooldowns.basic=cooldownFor('basic');playAttackPose(def.fx);const rolled=skillDamage(def,'basic');if(def.type==='projectile'){spawnProjectile(def,rolled);return}const hits=targetsInRange(def.range,{front:true,limit:1});spawnFx(def.fx,battle.x+55*battle.facing,150+battle.y,battle.facing);if(hits[0])damageEnemy(hits[0].i,rolled)}
function useCombatSlot(slot){const def=currentKit()[slot];if(!def||!battle)return;if((battle.cooldowns[slot]||0)>0){toast('Habilidade recarregando.');return}if(!spendEnergy(def.cost||0))return;battle.cooldowns[slot]=cooldownFor(slot);playAttackPose(def.fx);const rolled=skillDamage(def,slot);switch(def.type){case'melee':{spawnFx(def.fx,battle.x+65*battle.facing,155+battle.y,battle.facing);for(const t of targetsInRange(def.range,{front:true,limit:3}))damageEnemy(t.i,{value:rolled.value,crit:rolled.crit});break}case'projectile':spawnProjectile(def,rolled);break;case'multishot':for(let n=0;n<(def.shots||3);n++)spawnProjectile(def,rolled,{yOffset:(n-1)*10,damageScale:1});break;case'aoe':spawnFx(def.fx,battle.x,142+battle.y,1);for(const t of targetsInRange(def.range,{front:false,limit:99}))damageEnemy(t.i,{value:rolled.value,crit:rolled.crit});break;case'guard':battle.shieldT=def.duration||2;spawnFx(def.fx,battle.x,145+battle.y,1);toast('Guarda ativa: dano reduzido.');break;case'dash-hit':{const old=battle.x;battle.x=Math.max(30,Math.min(battle.worldW-80,battle.x+battle.facing*(def.distance||160)));spawnFx(def.fx,(old+battle.x)/2,145+battle.y,battle.facing);for(let i=0;i<battle.enemies.length;i++){const e=battle.enemies[i];if(e.dead)continue;if(e.x>=Math.min(old,battle.x)-30&&e.x<=Math.max(old,battle.x)+30)damageEnemy(i,{value:rolled.value,crit:rolled.crit})}break}case'dash':battle.x=Math.max(30,Math.min(battle.worldW-80,battle.x+battle.facing*(def.distance||140)));spawnFx(def.fx,battle.x,145+battle.y,battle.facing);break;case'teleport':{spawnFx(def.fx,battle.x,145+battle.y,battle.facing);battle.x=Math.max(30,Math.min(battle.worldW-80,battle.x+battle.facing*(def.distance||180)));battle.invulnT=.35;spawnFx(def.fx,battle.x,145+battle.y,battle.facing);break}case'multi-melee':{spawnFx(def.fx,battle.x+55*battle.facing,150+battle.y,battle.facing);const t=targetsInRange(def.range,{front:true,limit:1})[0];if(t){for(let h=0;h<(def.hits||3);h++)damageEnemy(t.i,{value:Math.max(1,Math.round(rolled.value/(def.hits||3))),crit:h===0&&rolled.crit})}break}case'backstab':{const t=targetsInRange(def.range,{front:false,limit:1})[0];if(!t){toast('Nenhum alvo próximo.');battle.cooldowns[slot]=0;state.player.energy=Math.min(state.player.maxEnergy,state.player.energy+(def.cost||0));renderHud();break}battle.x=Math.max(30,Math.min(battle.worldW-80,t.e.x-42*battle.facing));battle.invulnT=.25;spawnFx(def.fx,t.e.x,150,battle.facing);damageEnemy(t.i,rolled);break}case'vanish':battle.invulnT=def.duration||1.5;battle.x=Math.max(30,Math.min(battle.worldW-80,battle.x+battle.facing*(def.distance||120)));spawnFx(def.fx,battle.x,145+battle.y,battle.facing);toast('Desaparecer: invulnerável por alguns instantes.');break}}
function battleAction(a){if(!battle)return;if(a==='attack')basicAttack();else if(a==='q'||a==='e'||a==='r')useCombatSlot(a);else if(a==='jump'&&!battle.jump){battle.vy=440;battle.jump=true}else if(a==='dodge'&&battle.dodgeCd<=0){battle.x+=battle.facing*120;battle.x=Math.max(30,Math.min(battle.worldW-80,battle.x));battle.dodgeCd=.8;battle.invulnT=.25;spawnFx('dodge',battle.x,142+battle.y,battle.facing)}else if(a==='f'&&battle.enemies.every(e=>e.dead)){if(Math.abs(battle.x-battle.portalX)>140)return toast('Aproxime-se do portal de retorno.');state.missions.goblin.ready=true;state.missions.goblin.kills=5;save();stopBattle();toast('Missão concluída. Retorne à Guilda e fale com Elena.');go('guild')}}
function loopBattle(t){if(!battle)return;const dt=Math.min(.033,(t-last)/1000||.016);last=t;for(const k of Object.keys(battle.cooldowns))battle.cooldowns[k]=Math.max(0,battle.cooldowns[k]-dt);battle.dodgeCd=Math.max(0,battle.dodgeCd-dt);battle.shieldT=Math.max(0,battle.shieldT-dt);battle.invulnT=Math.max(0,battle.invulnT-dt);battle.attackAnimT=Math.max(0,battle.attackAnimT-dt);let mv=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0);battle.crouch=keys.has('KeyS')&&!battle.jump;if(mv&&!battle.crouch){battle.facing=mv;const speed=215+(state.player.attributes?.AGI||0)*2.4;battle.x+=mv*speed*dt}battle.x=Math.max(30,Math.min(battle.worldW-80,battle.x));if(battle.jump){battle.y+=battle.vy*dt;battle.vy-=980*dt;if(battle.y<=0){battle.y=0;battle.vy=0;battle.jump=false}}for(let i=0;i<battle.enemies.length;i++){const e=battle.enemies[i];e.hitT=Math.max(0,(e.hitT||0)-dt);e.attackT=Math.max(0,(e.attackT||0)-dt);if(e.dead){syncEnemyDom(i,e);continue}e.cd=Math.max(0,e.cd-dt);const dx=battle.x-e.x,dist=Math.abs(dx);e.facing=dx<0?-1:1;e.moving=dist<310&&dist>68&&e.attackT<=0;if(e.moving)e.x+=Math.sign(dx)*(50+state.player.level*.5)*dt;if(dist<62&&e.cd<=0){e.cd=.95;e.attackT=.28;e.moving=false;if(battle.invulnT<=0){let dmg=5+Math.floor(state.player.level/3);if(battle.shieldT>0)dmg=Math.max(1,Math.round(dmg*.35));state.player.hp=Math.max(1,state.player.hp-dmg);renderHud();damageNumber(battle.x+22,dmg,false)}}syncEnemyDom(i,e)}updateProjectiles(dt);const p=$('#battlePlayer');if(p){p.style.left=`${battle.x}px`;p.style.bottom=`${94+battle.y}px`;paintSprite(p,state.player.class,battle.facing<0?'left':'right');p.classList.toggle('crouch',battle.crouch);p.classList.toggle('walking',!!mv&&!battle.jump&&!battle.crouch);p.classList.toggle('jumping',battle.jump);p.classList.toggle('shielded',battle.shieldT>0);p.classList.toggle('vanished',battle.invulnT>.3&&state.player.class==='Ladino');p.dataset.attack=battle.attackAnimT>0?battle.attackAnimKind:''}const viewport=$('#battleViewport'),scene=$('#battleScene');if(viewport&&scene){const vw=viewport.clientWidth||800;const maxCam=Math.max(0,battle.worldW-vw);battle.cameraX=Math.max(0,Math.min(maxCam,battle.x-vw*.40));scene.style.transform=`translate3d(${-battle.cameraX}px,0,0)`}raf=requestAnimationFrame(loopBattle)}
function stopBattle(){if(raf)cancelAnimationFrame(raf);raf=0;keys.clear();battle=null}
function init(){document.documentElement.style.setProperty('--auth-bg',ART.scenes?.city?`url('${ART.scenes.city}')`:'');renderClassPicks();$$('[data-auth-tab]').forEach(b=>b.onclick=()=>authTab(b.dataset.authTab));$('#guestBtn').onclick=showGame;$('#loginForm').onsubmit=e=>{e.preventDefault();const n=$('#loginName').value.trim();if(n)state.player.name=n;save();showGame()};$('#registerForm').onsubmit=e=>{e.preventDefault();const n=$('#regName').value.trim(),pass=$('#regPassword').value;if(n.length<2)return toast('Digite um nome com pelo menos 2 caracteres.');if(pass.length<6)return toast('Senha precisa ter pelo menos 6 caracteres.');state=defaultState();state.player.name=n;state.player.class=selectedRegisterClass;state.player.attributes=generatedAttributes(selectedRegisterClass);state.player.attributePoints=0;state.account.email=$('#regEmail').value.trim();syncDerived();state.player.hp=state.player.maxHp;state.player.energy=state.player.maxEnergy;save();showGame()};$$('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));$('#brandHome').onclick=()=>go('city');$('#mobileNavToggle').onclick=()=>$('#sideNav').classList.toggle('open');$$('[data-chat]').forEach(b=>b.onclick=()=>{state.ui.chat=b.dataset.chat;save();renderChat()});$('#chatForm').onsubmit=e=>{e.preventDefault();const i=$('#chatInput'),v=i.value.trim();if(!v)return;addChat(state.ui.chat,state.player.name,v);i.value=''};addEventListener('keydown',e=>{if(['KeyA','KeyD','KeyW','KeyS','KeyQ','KeyE','KeyR','KeyF','Space','ShiftLeft','ShiftRight'].includes(e.code)){keys.add(e.code);if(battle){e.preventDefault();if(e.code==='Space'&&!e.repeat)battleAction('attack');if(e.code==='KeyQ'&&!e.repeat)battleAction('q');if(e.code==='KeyE'&&!e.repeat)battleAction('e');if(e.code==='KeyR'&&!e.repeat)battleAction('r');if(e.code==='KeyW'&&!e.repeat)battleAction('jump');if((e.code==='ShiftLeft'||e.code==='ShiftRight')&&!e.repeat)battleAction('dodge');if(e.code==='KeyF'&&!e.repeat)battleAction('f')}}},{passive:false});addEventListener('keyup',e=>keys.delete(e.code));if(localStorage.getItem(KEY)||LEGACY_KEYS.some(k=>localStorage.getItem(k)))$('#guestBtn').textContent='Continuar progresso existente'}
init();})();