window.DESPERTAR_ART={
  scenes:{
    city:'assets/real/city.webp',
    guild:'assets/real/guild.webp',
    battle:'assets/real/city.webp'
  },
  portraits:{
    elena:'assets/real/elena.webp'
  },
  classes:{
    Guerreiro:{sheet:'assets/real/guerreiro-sheet.png'},
    Mago:{sheet:'assets/real/mago-sheet.png'},
    Arqueiro:{sheet:'assets/real/arqueiro-sheet.png'},
    Ladino:{sheet:'assets/real/ladino-sheet.png'}
  },
  mobs:{
    goblin:{
      sheet:'assets/real/goblin-sheet.png',
      frames:{idle:0,walk1:1,walk2:2,attack:3,hit:4,dead:5}
    }
  },
  portal:'assets/real/portal.png',
  frames:{front:0,right:2,left:6,back:4}
};