window.DESPERTAR_ART={
  scenes:{
    city:'assets/real/city.webp',
    guild:'assets/real/guild.webp'
  },
  portraits:{
    elena:'assets/real/elena.webp'
  },
  classes:{
    Guerreiro:{sheet:'assets/real/guerreiro-sheet.png'},
    Mago:{sheet:'assets/real/mago-sheet.png'},
    Arqueiro:{sheet:'assets/real/arqueiro-sheet.png'},
    Ladino:{sheet:'assets/real/ladino-sheet.png'}
  },
  frames:{front:0,right:2,left:6,back:4}
};