from pathlib import Path
import re

p=Path('_site/index.html')
s=p.read_text(encoding='utf-8')

def rep(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f'{label} not found')
    s=s.replace(old,new,1)

def sub(pattern,repl,label):
    global s
    s2,n=re.subn(pattern,repl,s,count=1,flags=re.S)
    if n!=1:
        raise SystemExit(f'{label} replacement count={n}')
    s=s2

s=s.replace('v0.7.3','v0.7.4')

# Chapter 2 map and travel point from Orla.
old_map="function mapForWorld(){return world==='city'?city:world==='guild'?guild:world==='orla'?orla:world==='cistern'?cistern:camp}"
new_map="""const roadDeparture={x:1470,y:165,r:38};
const road={w:1800,h:900,returnGate:{x:105,y:760,r:38},lio:{x:255,y:260,r:22},firstGate:{x:510,y:520,r:34},finalGate:{x:1580,y:470,r:42},lanterns:[{id:'l1',x:650,y:330},{id:'l2',x:970,y:555},{id:'l3',x:1280,y:310}],manifests:[{id:'m1',x:735,y:640,name:'Manifesto rasgado'},{id:'m2',x:1080,y:235,name:'Livro de passageiros'},{id:'m3',x:1390,y:625,name:'Recibo de carga'}],obstacles:[]};
function mapForWorld(){return world==='city'?city:world==='guild'?guild:world==='orla'?orla:world==='cistern'?cistern:world==='road'?road:camp}"""
rep(old_map,new_map,'road map')

# Make chapter number scale automatically as missions advance.
sub(r"function campaignReward\(id,next,xp,gold,drop\)\{.*?\}\nfunction campaignObjective",r'''function campaignReward(id,next,xp,gold,drop){const st=ensureCampaignMain();if(st.completed.includes(id))return;gainXP(xp);player.gold=Number(player.gold||0)+gold;if(drop)addItem(drop,1);st.completed.push(id);st.mission=next;const num=parseInt(String(next||'mq_01').split('_')[1]||'1',10);st.chapter=Math.max(1,Math.ceil(num/4));st.progress={};writeCampaignMain(st);save();updateHud();const item=drop?` • Drop: ${drop}`:'';toastMsg(`Missão concluída: +${xp} EXP • +${gold} Ouro${item}`);window.dispatchEvent(new CustomEvent('despertar:campaign-progress'))}
function campaignObjective''','campaign reward')

sub(r"function campaignObjective\(\)\{.*?\}\nfunction startEntreVeus",r'''function campaignObjective(){const st=readCampaignMain();if(!st||!st.unlocked)return'Fale com Raul Vilar para receber a próxima missão.';const pr=st.progress||{},cm=st.mission;if(cm==='mq_01')return world==='orla'?'Entregue a caixa de filtros para Saira Vento.':'Vá até a caravana marcada e viaje para Orla.';if(cm==='mq_02')return`Resgate os moradores da área alagada (${(pr.rescued||[]).length}/3).`;if(cm==='mq_03')return (pr.clues||[]).length<3?`Investigue as inconsistências da rua (${(pr.clues||[]).length}/3).`:'Fale com Inês Lume e compare as três evidências.';if(cm==='mq_04'){if(world!=='cistern')return'Entre na Cisterna e investigue o padrão.';if((pr.valves||[]).length<3)return`Interrompa as válvulas do padrão (${(pr.valves||[]).length}/3).`;return pr.bossDefeated?'Use o portal de retorno.':'Derrote o Síndico da Cisterna.'}if(cm==='mq_05'){if(world!=='road')return'Vá até a saída de Orla e siga para a Estrada das Lanternas.';return pr.metLio?'Leve os remédios com Lio até a primeira cancela.':'Fale com Lio na entrada da estrada.'}if(cm==='mq_06'){const a=(pr.lanterns||[]).length,k=(pr.roadKills||[]).length;return`Reative as lanternas (${a}/3) e elimine as Sombras de Pedágio (${k}/3).`}if(cm==='mq_07'){const n=(pr.manifests||[]).length;return n<3?`Recupere os manifestos adulterados (${n}/3).`:'Volte até Lio e compare os registros.'}if(cm==='mq_08')return pr.bossDefeated?'A passagem foi liberada.':'Enfrente O Cobrador na cancela final.';if(cm==='mq_09')return'Capítulo 2 concluído. Retorne a Orla. Nova missão: Livro de pagamento.';return'Continue a campanha principal.'}
function startEntreVeus''','chapter2 objectives')

# Chapter 2 helpers and NPC dialogue.
marker="function travelOrla(){world='orla';player.x=180;player.y=735;projectiles=[];goblins=[];save();updateHud();toastMsg('Orla — Distrito da Cisterna')}"
helpers=r'''function travelRoad(){const st=ensureCampaignMain();if(!['mq_05','mq_06','mq_07','mq_08','mq_09'].includes(st.mission)){toastMsg('A estrada ainda não faz parte da sua missão atual.');return}world='road';player.x=150;player.y=720;projectiles=[];if(st.mission==='mq_05'){const inv=ensureInventory();if(!inv['Caixa de Remédios'])addItem('Caixa de Remédios',1)}spawnRoadEncounter();save();updateHud();toastMsg('Estrada das Lanternas')}
function returnOrlaFromRoad(){world='orla';player.x=1390;player.y=205;projectiles=[];goblins=[];save();updateHud();toastMsg('Retorno a Orla')}
function spawnRoadEncounter(){const st=ensureCampaignMain(),pr=st.progress||{};goblins=[];if(st.mission==='mq_06'){const killed=pr.roadKills||[];const pts=[{id:201,x:720,y:405},{id:202,x:1040,y:620},{id:203,x:1360,y:385}];goblins=pts.filter(e=>!killed.includes(e.id)).map(e=>({...e,r:19,hp:42,maxHp:42,dead:false,state:'idle',cooldown:.55+Math.random()*.5,windup:0,attackX:0,attackY:0,roadEnemy:true,name:'Sombra de Pedágio'}))}else if(st.mission==='mq_08'&&!pr.bossDefeated){const hp=Math.max(1,Number(pr.bossHp||260));goblins=[{x:1515,y:470,r:31,hp,maxHp:260,dead:false,id:280,state:'idle',cooldown:.65,windup:0,attackX:0,attackY:0,roadBoss:true,boss:true,name:'O Cobrador'}]}}
function checkMQ06(){const st=ensureCampaignMain(),pr=st.progress||{};if(st.mission!=='mq_06')return;const lit=(pr.lanterns||[]).length,kills=(pr.roadKills||[]).length;if(lit>=3&&kills>=3){goblins=[];campaignReward('mq_06','mq_07',110,70,'Pavio de Vigília');toastMsg('Nova missão: A soma dos passageiros')}}
function talkLio(){const st=ensureCampaignMain(),pr=st.progress||{},cm=st.mission;if(cm==='mq_05'){setDialog(`<b>${player.name}</b><br><br>Você é o Lio? Vim acompanhar os remédios pela Estrada das Lanternas.<br><br><b>Lio — Mensageiro da estrada</b><br><br>Sou eu. Ainda bem que mandaram um Desperto. A estrada continua aberta, mas as cancelas começaram a cobrar nomes de pessoas que não aparecem em registro nenhum.`,[['Vamos seguir',()=>{pr.metLio=true;st.progress=pr;writeCampaignMain(st);closeDialog();save();updateHud();toastMsg('Lio seguirá até a primeira cancela.')}],['Quem é você?',()=>setDialog('<b>Lio</b><br><br>Eu faço entregas entre Orla e os povoados da estrada. Antes dos Portais eu era aprendiz de carteiro. Depois da Catástrofe, entregar uma carta ou um remédio virou trabalho de risco.<br><br>Conheço cada posto desta rota, e justamente por isso sei que esses nomes novos nas cancelas não deveriam estar aqui.',[['Voltar',()=>talkLio()],['Encerrar',closeDialog]])],['O que está acontecendo?',()=>setDialog('<b>Lio</b><br><br>As lanternas marcam o caminho seguro. Quando começaram a apagar, surgiram cobranças estranhas nos postos. Quem não entrega um nome fica preso na rota. O pior é que ninguém sabe quem são as pessoas cobradas.',[['Voltar',()=>talkLio()],['Encerrar',closeDialog]])],['Depois',closeDialog]]);return}if(cm==='mq_07'){if((pr.manifests||[]).length<3){setDialog(`<b>${player.name}</b><br><br>Lio, encontrei registros adulterados, mas ainda faltam documentos.<br><br><b>Lio</b><br><br>Então continue procurando. Precisamos de cópias de postos diferentes para provar que não é um erro isolado.`);return}setDialog(`<b>${player.name}</b><br><br>Lio, achei três registros. Pessoas estão sendo contabilizadas como se fossem carga.<br><br><b>Lio</b><br><br>Então é isso. Os pedágios estão lucrando com gente que oficialmente não existe. Leve uma cópia, eu fico com outra. A cancela final vai tentar impedir que esses documentos saiam daqui.`,[['Comparar e registrar manifestos',()=>{closeDialog();campaignReward('mq_07','mq_08',130,90,'Manifesto de Passageiros');spawnRoadEncounter();toastMsg('Nova missão: Passagem contestada')}],['Quem é você?',()=>setDialog('<b>Lio</b><br><br>Sou mensageiro. Hoje, pelo visto, também virei testemunha.',[['Voltar',()=>talkLio()],['Encerrar',closeDialog]])],['Depois',closeDialog]]);return}if(cm==='mq_08'){setDialog(`<b>${player.name}</b><br><br>A cancela final está bloqueada.<br><br><b>Lio</b><br><br>É O Cobrador. Ele transforma recibos em correntes e tenta fazer todo mundo aceitar a conta sem perguntar quem está pagando. Não deixe os manifestos chegarem às mãos dele.`,[['Vou enfrentar ele',closeDialog],['Depois',closeDialog]]);return}setDialog('<b>Lio</b><br><br>A estrada nunca foi tranquila, mas pelo menos agora sabemos onde começa a mentira.')}
function inspectRoadGate(){const st=ensureCampaignMain(),pr=st.progress||{};if(st.mission!=='mq_05')return;if(!pr.metLio){toastMsg('Fale com Lio antes de seguir.');return}setDialog(`<b>${player.name}</b><br><br>Chegamos à cancela. Tenho os remédios para o posto seguinte.<br><br><b>Lio</b><br><br>Olhe a lista presa na madeira. Eles estão cobrando passagem em nome de três pessoas que nunca constaram nos registros da rota. Isso começou depois que as lanternas apagaram.`,[['Entregar remédios e registrar a lista',()=>{removeItem('Caixa de Remédios',1);closeDialog();campaignReward('mq_05','mq_06',70,45,'Lista de Pedágio');spawnRoadEncounter();toastMsg('Nova missão: Três luzes acesas')}],['Depois',closeDialog]])}
function activateRoadLantern(id){const st=ensureCampaignMain(),pr=st.progress||{};if(st.mission!=='mq_06')return;pr.lanterns=pr.lanterns||[];if(pr.lanterns.includes(id)){toastMsg('Lanterna já acesa.');return}pr.lanterns.push(id);st.progress=pr;writeCampaignMain(st);save();toastMsg(`Lanterna reativada ${pr.lanterns.length}/3`);checkMQ06()}
function collectRoadManifest(id,name){const st=ensureCampaignMain(),pr=st.progress||{};if(st.mission!=='mq_07')return;pr.manifests=pr.manifests||[];if(pr.manifests.includes(id)){toastMsg('Documento já recolhido.');return}setDialog(`<b>${name}</b><br><br>O documento separa mercadorias e passageiros em colunas diferentes, mas alguns nomes foram transferidos para a coluna de carga.`,[['Guardar cópia',()=>{pr.manifests.push(id);st.progress=pr;writeCampaignMain(st);closeDialog();save();updateHud();toastMsg(`Manifesto ${pr.manifests.length}/3 recuperado`)}],['Depois',closeDialog]])}
'''
rep(marker,helpers+'\n'+marker,'chapter2 helpers')

# Existing saves can reload directly on the road.
sub(r"function load\(\)\{.*?\}\nfunction showGame",r"""function load(){try{const s=JSON.parse(localStorage.getItem(SAVE));if(!s)return false;player=s.player;ensureInventory();world=s.world||'city';mission=s.mission||S.GO_GUILD;if(world==='camp'){spawnGoblins();(s.goblins||[]).forEach((v,i)=>Object.assign(goblins[i],v))}else if(world==='cistern'){spawnCisternBoss()}else if(world==='road'){spawnRoadEncounter()}showGame();return true}catch{return false}}
function showGame""",'load road')

# Combat support and drops on the road.
s=s.replace("if(world!=='camp'&&world!=='cistern'){updateHud();return}","if(world!=='camp'&&world!=='cistern'&&world!=='road'){updateHud();return}",1)
s=s.replace("if(world==='camp'||world==='cistern'){for(const p of projectiles)","if(world==='camp'||world==='cistern'||world==='road'){for(const p of projectiles)",1)
s=s.replace("if(!((world==='cistern'?cistern:camp).obstacles||[]).some(o=>circleRectHit(nx,ny,g.r,o)))","if(!(mapForWorld().obstacles||[]).some(o=>circleRectHit(nx,ny,g.r,o)))",1)

sub(r"function hitGoblin\(g,d\)\{.*?\}\nfunction basicAttack",r'''function hitGoblin(g,d){if(g.dead)return;g.hp-=d;if(g.hp<=0){g.hp=0;g.dead=true;g.state='dead';if(world==='camp'){gainXP(8);player.gold=Number(player.gold||0)+5;addItem('Fragmento de Goblin',1);toastMsg('Drop: +8 EXP • +5 Ouro • Fragmento de Goblin');save()}else if(world==='cistern'&&g.boss){const st=ensureCampaignMain(),pr=st.progress||{};pr.bossDefeated=true;pr.bossHp=0;st.progress=pr;writeCampaignMain(st);campaignReward('mq_04','mq_05',180,120,'Inscrição de Namar');toastMsg('BOSS derrotado • Drop: Inscrição de Namar • Capítulo 1 concluído')}else if(world==='road'&&g.roadBoss){const st=ensureCampaignMain(),pr=st.progress||{};pr.bossDefeated=true;pr.bossHp=0;st.progress=pr;writeCampaignMain(st);campaignReward('mq_08','mq_09',240,180,'Selo do Cobrador');goblins=[];toastMsg('O Cobrador derrotado • Capítulo 2 concluído')}else if(world==='road'&&g.roadEnemy){const st=ensureCampaignMain(),pr=st.progress||{};pr.roadKills=pr.roadKills||[];if(!pr.roadKills.includes(g.id))pr.roadKills.push(g.id);st.progress=pr;writeCampaignMain(st);gainXP(12);player.gold=Number(player.gold||0)+7;addItem('Fragmento de Lacre',1);save();toastMsg('Drop: +12 EXP • +7 Ouro • Fragmento de Lacre');checkMQ06()}}else if(world==='cistern'&&g.boss){const st=ensureCampaignMain(),pr=st.progress||{};pr.bossHp=g.hp;st.progress=pr;writeCampaignMain(st)}else if(world==='road'&&g.roadBoss){const st=ensureCampaignMain(),pr=st.progress||{};pr.bossHp=g.hp;st.progress=pr;writeCampaignMain(st)}updateHud()}
function basicAttack''','road combat drops')

sub(r"function hurtPlayer\(d\)\{.*?\}\nfunction updateGoblin",r'''function hurtPlayer(d){player.hp=Math.max(0,player.hp-d);dangerFlash.style.opacity=.28;setTimeout(()=>dangerFlash.style.opacity=0,110);if(player.hp<=0){player.hp=player.maxHp;const sp=world==='cistern'?{x:130,y:630}:world==='road'?{x:150,y:720}:{x:160,y:610};player.x=sp.x;player.y=sp.y;for(const g of goblins){if(!g.dead){g.state='idle';g.cooldown=.8;g.windup=0}}toastMsg('Você caiu e retornou ao ponto seguro.');save()}updateHud()}
function updateGoblin''','road respawn')

# Road interactions are added just before the existing Goblin return interaction.
camp_return=" if(world==='camp'&&goblins.filter(g=>g.dead).length>=5&&near(camp.returnPortal,86)){setDialog('<b>Portal de retorno</b><br>A missão foi concluída. Volte à Guilda para entregar a prova.',[['Retornar à cidade',()=>{closeDialog();returnCity()}],['Ficar',closeDialog]])}"
road_interactions=r''' if(world==='orla'){
  const cm=currentCampaignMission();if(['mq_05','mq_06','mq_07','mq_08','mq_09'].includes(cm)&&near(roadDeparture,88)){travelRoad();return}
 }
 if(world==='road'){
  const cm=currentCampaignMission(),pr=progressMain();
  if(near(road.returnGate,82)){returnOrlaFromRoad();return}
  if(near(road.lio,76)){talkLio();return}
  if(cm==='mq_05'&&near(road.firstGate,78)){inspectRoadGate();return}
  if(cm==='mq_06'){for(const l of road.lanterns)if(!(pr.lanterns||[]).includes(l.id)&&near(l,72)){activateRoadLantern(l.id);return}}
  if(cm==='mq_07'){for(const m of road.manifests)if(!(pr.manifests||[]).includes(m.id)&&near(m,72)){collectRoadManifest(m.id,m.name);return}}
 }
'''
rep(camp_return,road_interactions+camp_return,'road interactions')

# Target arrows now guide Chapter 2 too.
sub(r"function target\(\)\{.*?\}\nfunction arrowToTarget",r'''function target(){if(world==='camp'&&mission===S.GOBLINS){const alive=goblins.find(g=>!g.dead);return alive||camp.returnPortal}if(world==='city'){if(mission===S.GO_GUILD||mission===S.RETURN_GUILD)return city.guildDoor;if(mission===S.PORTAL)return city.portal;if(mission===S.DONE&&currentCampaignMission())return orlaDeparture}if(world==='guild'){if(mission===S.REGISTER||mission===S.REPORT)return guild.reception;if(mission===S.CAPTAIN||mission===S.CAPTAIN_AFTER)return guild.captain;if(mission===S.BOARD)return guild.board;if(mission===S.PORTAL)return guild.exit}if(world==='orla'){const cm=currentCampaignMission(),pr=progressMain();if(cm==='mq_01')return orla.saira;if(cm==='mq_02')return orla.residents.find(r=>!(pr.rescued||[]).includes(r.id))||orla.saira;if(cm==='mq_03')return orla.clues.find(q=>!(pr.clues||[]).includes(q.id))||orla.ines;if(cm==='mq_04')return orla.cisternDoor;if(['mq_05','mq_06','mq_07','mq_08','mq_09'].includes(cm))return roadDeparture}if(world==='cistern'){const cm=currentCampaignMission(),pr=progressMain();if(cm==='mq_04'){const v=cistern.valves.find(v=>!(pr.valves||[]).includes(v.id));if(v)return v;return goblins.find(g=>!g.dead)||cistern.exit}if(cm==='mq_05')return cistern.returnPortal}if(world==='road'){const cm=currentCampaignMission(),pr=progressMain();if(cm==='mq_05')return pr.metLio?road.firstGate:road.lio;if(cm==='mq_06'){const l=road.lanterns.find(x=>!(pr.lanterns||[]).includes(x.id));if(l)return l;return goblins.find(g=>!g.dead)||road.lio}if(cm==='mq_07')return road.manifests.find(m=>!(pr.manifests||[]).includes(m.id))||road.lio;if(cm==='mq_08')return goblins.find(g=>!g.dead)||road.finalGate;if(cm==='mq_09')return road.returnGate}return null}
function arrowToTarget''','chapter2 targets')

# Road drawing and route marker in Orla.
insert_draw=r'''function drawRoadDepartureMarker(){const cm=currentCampaignMission();if(!['mq_05','mq_06','mq_07','mq_08','mq_09'].includes(cm))return;ctx.fillStyle='#5b4630';ctx.fillRect(roadDeparture.x-45,roadDeparture.y-24,90,48);ctx.fillStyle='#c89f58';ctx.fillRect(roadDeparture.x+28,roadDeparture.y-62,8,44);label('ESTRADA DAS LANTERNAS',roadDeparture.x-95,roadDeparture.y-72,'#f2d79a',13)}
function drawRoad(){ctx.fillStyle='#292b2b';ctx.fillRect(0,0,road.w,road.h);ctx.fillStyle='#554a38';ctx.fillRect(80,420,1640,150);ctx.fillStyle='#3b372d';for(let x=200;x<1700;x+=230){ctx.fillRect(x,120,100,80);ctx.fillRect(x,665,110,70)}label('ESTRADA DAS LANTERNAS',650,85,'#e6cf96',20);label('Retorno a Orla',55,710,'#ddd');ctx.fillStyle='#6c5940';ctx.fillRect(road.firstGate.x-36,road.firstGate.y-65,72,130);label('1ª CANCELA',road.firstGate.x-45,road.firstGate.y-78,'#e8d6ad');ctx.fillStyle='#5c4938';ctx.fillRect(road.finalGate.x-52,road.finalGate.y-85,104,170);label('CANCELA FINAL',road.finalGate.x-55,road.finalGate.y-98,'#e8d6ad');const cm=currentCampaignMission(),pr=progressMain();npc(road.lio.x,road.lio.y,'Lio','#b7a27c',cm==='mq_05'||(cm==='mq_07'&&(pr.manifests||[]).length>=3));for(const l of road.lanterns){const lit=(pr.lanterns||[]).includes(l.id);ctx.fillStyle=lit?'#e7c868':'#564c3c';ctx.fillRect(l.x-8,l.y-44,16,52);ctx.beginPath();ctx.arc(l.x,l.y-48,lit?17:13,0,Math.PI*2);ctx.fill();if(cm==='mq_06')label(lit?'Acesa':'Lanterna',l.x-28,l.y-72,lit?'#ffe58d':'#aaa')}if(cm==='mq_07')for(const m of road.manifests)if(!(pr.manifests||[]).includes(m.id)){ctx.fillStyle='#d8c9a3';ctx.fillRect(m.x-15,m.y-11,30,22);label(m.name,m.x-55,m.y-22,'#f1dfb3')}for(const g of goblins){if(g.dead)continue;if(g.state==='windup'){ctx.fillStyle='#d33a';ctx.beginPath();ctx.arc(g.attackX,g.attackY,g.roadBoss?62:48,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ff6565';ctx.stroke()}ctx.fillStyle=g.roadBoss?'#8c6c4f':'#6f665b';ctx.beginPath();ctx.arc(g.x,g.y,g.r,0,Math.PI*2);ctx.fill();label(g.name||'Sombra de Pedágio',g.x-(g.roadBoss?42:48),g.y-g.r-12,g.roadBoss?'#f1d2a2':'#ddd0bd',g.roadBoss?15:12);ctx.fillStyle='#222';ctx.fillRect(g.x-35,g.y+g.r+9,70,6);ctx.fillStyle='#b84b4b';ctx.fillRect(g.x-35,g.y+g.r+9,70*g.hp/g.maxHp,6)}}
'''
s=s.replace('function drawCamp(){',insert_draw+'function drawCamp(){',1)

sub(r"function draw\(\)\{.*?\}\nfunction label",r'''function draw(){ctx.clearRect(0,0,W,H);if(!player)return;const map=mapForWorld();cam.x=Math.max(0,Math.min(map.w-W,player.x-W/2));cam.y=Math.max(0,Math.min(map.h-H,player.y-H/2));ctx.save();ctx.translate(-cam.x,-cam.y);if(world==='city')drawCity();else if(world==='guild')drawGuild();else if(world==='orla'){drawOrla();drawRoadDepartureMarker()}else if(world==='cistern')drawCistern();else if(world==='road')drawRoad();else drawCamp();drawPlayer();ctx.restore();arrowToTarget();drawAim();updateHint()}
function label''','road draw loop')

# Interaction hints.
sub(r"function currentInteract\(\)\{.*?\}\nfunction updateHint",r'''function currentInteract(){if(!player)return'';if(world==='city'){if(near(city.guildDoor,82))return'Entrar na Guilda';if(near({x:470,y:500},78))return'Davi Moura';if(near({x:1080,y:480},78))return'Breno Carvalho';if(near(city.portal,82)&&mission===S.PORTAL)return'Portal Rank F';const cs=readCampaignMain();if(cs&&cs.unlocked&&near(orlaDeparture,82))return'Viajar para Orla'}if(world==='guild'){if(near(guild.exit,82))return'Sair da Guilda';if(near(guild.reception,78))return'Elena Duarte';if(near(guild.captain,78))return'Raul Vilar';if(near({x:520,y:290},76))return'Caio Nunes';if(near({x:570,y:360},76))return'Mirela Santos';if(near(guild.board,78))return'Quadro de Missões'}if(world==='orla'){const cm=currentCampaignMission(),pr=progressMain();if(near(orla.returnGate,82))return'Voltar à Cidade Inicial';if(near(orla.saira,78))return'Saira Vento';if(near(orla.ines,78))return'Inês Lume';if(['mq_05','mq_06','mq_07','mq_08','mq_09'].includes(cm)&&near(roadDeparture,88))return'Seguir pela Estrada das Lanternas';if(cm==='mq_02'&&orla.residents.some(r=>!(pr.rescued||[]).includes(r.id)&&near(r,75)))return'Resgatar morador';if(cm==='mq_03'&&orla.clues.some(q=>!(pr.clues||[]).includes(q.id)&&near(q,75)))return'Investigar evidência';if(cm==='mq_04'&&near(orla.cisternDoor,90))return'Entrar na Cisterna'}if(world==='cistern'){const cm=currentCampaignMission(),pr=progressMain();if(cm==='mq_04'&&near(cistern.exit,82))return'Sair da Cisterna';if(cm==='mq_04'&&cistern.valves.some(v=>!(pr.valves||[]).includes(v.id)&&near(v,75)))return'Interromper válvula';if(cm==='mq_05'&&near(cistern.returnPortal,88))return'Retornar a Orla'}if(world==='road'){const cm=currentCampaignMission(),pr=progressMain();if(near(road.returnGate,82))return'Voltar para Orla';if(near(road.lio,78))return'Lio';if(cm==='mq_05'&&near(road.firstGate,78))return'Inspecionar a cancela';if(cm==='mq_06'&&road.lanterns.some(l=>!(pr.lanterns||[]).includes(l.id)&&near(l,75)))return'Reativar lanterna';if(cm==='mq_07'&&road.manifests.some(m=>!(pr.manifests||[]).includes(m.id)&&near(m,75)))return'Recolher manifesto'}if(world==='camp'&&goblins.filter(g=>g.dead).length>=5&&near(camp.returnPortal,82))return'Portal de retorno';return''}
function updateHint''','road hints')

# Direct click on Lio follows the same dialogue model as the Guild NPCs.
needle="if(world==='city'&&near({x:1080,y:480},90)&&clicked({x:1080,y:480},34)){talkBreno();return}basicAttack(wx-player.x,wy-player.y)"
replace="if(world==='city'&&near({x:1080,y:480},90)&&clicked({x:1080,y:480},34)){talkBreno();return}if(world==='road'&&near(road.lio,90)&&clicked(road.lio,36)){talkLio();return}basicAttack(wx-player.x,wy-player.y)"
rep(needle,replace,'Lio mouse interaction')

for needle in ['Estrada das Lanternas','O Cobrador','Sombra de Pedágio','Manifesto de Passageiros','Fragmento de Lacre','mq_08','mq_09']:
    if needle not in s:
        raise SystemExit(f'validation failed: {needle}')

p.write_text(s,encoding='utf-8')
