from pathlib import Path
import re

p=Path('_site/index.html')
s=p.read_text(encoding='utf-8')

def rep(old,new,label,count=1):
    global s
    n=s.count(old)
    if n < count:
        raise SystemExit(f'{label}: expected >= {count}, found {n}')
    s=s.replace(old,new,count)

def sub(pattern,repl,label,count=1):
    global s
    s2,n=re.subn(pattern,repl,s,count=count,flags=re.S)
    if n!=count:
        raise SystemExit(f'{label}: replacement count={n}')
    s=s2

s=s.replace('v0.9.0','v0.9.1')
rep("#mainMenuBar{position:absolute;z-index:15;", "#mainMenuBar{position:absolute;z-index:40;", 'menu z')
rep("#combatHotbar{position:absolute;z-index:14;", "#combatHotbar{position:absolute;z-index:39;", 'combat z')
rep("#dialog.portrait-elena:before{content:'';background-image:url('assets/sprites/elena-portrait.svg')}", "#dialog.portrait-elena:before{content:'';background-image:url('assets/portraits/elena.webp')}#dialog.portrait-raul:before{content:'';background-image:url('assets/portraits/raul.webp')}", 'portraits')
rep(".class-art{position:absolute;left:50%;top:7px;transform:translateX(-50%);width:96px;height:96px;background-repeat:no-repeat;background-size:800% 100%;image-rendering:pixelated;filter:drop-shadow(0 5px 5px #000)}", ".class-art{position:absolute;left:50%;top:7px;transform:translateX(-50%);width:96px;height:96px;background-repeat:no-repeat;background-size:800% 100%;background-position:0 0;image-rendering:pixelated;filter:drop-shadow(0 5px 5px #000)}#mainMenuBar button,#combatHotbar button,.scene-hotspot{touch-action:manipulation;-webkit-tap-highlight-color:transparent}#sideControlHint{position:absolute;z-index:38;left:50%;bottom:74px;transform:translateX(-50%);display:none;padding:6px 10px;background:#06101bd9;border:1px solid #806b49;color:#f3dfb0;font:700 11px system-ui;pointer-events:none;white-space:nowrap}", 'class art css')
rep('</div>\n<div id="hud" style="display:none">','</div>\n<div id="sideControlHint">A / D mover • W pular • S agachar • Q / E / R habilidades • F interagir</div>\n<div id="hud" style="display:none">','side hint html')
sub(r"function setDialog\(text,actions=\[\['Fechar',closeDialog\]\]\)\{.*?dialog\.style\.display='block'\}", """function setDialog(text,actions=[['Fechar',closeDialog]]){dialog.classList.toggle('portrait-elena',/Elena Duarte|<b>Elena<\\/b>/.test(text));dialog.classList.toggle('portrait-raul',/Raul Vilar|Capitão Raul|<b>Raul<\\/b>/.test(text));dialogText.innerHTML=text;dialogActions.innerHTML='';for(const [label,fn] of actions){const b=document.createElement('button');b.className='btn';b.textContent=label;b.type='button';b.addEventListener('click',fn);dialogActions.appendChild(b)}dialog.style.display='block'}""",'setDialog')
sub(r"const classSpritePaths=\{.*?\};const classSpriteImages=\{\};for\(const\[k,v\]of Object\.entries\(classSpritePaths\)\)\{const i=new Image;i\.src=v;classSpriteImages\[k\]=i\}function sideCombatWorld\(\)\{return world==='camp'\|\|world==='rift'\}function sideGroundY\(\)\{return 430\}", """const classSpritePaths={Guerreiro:'assets/characters/guerreiro/sheet.png',Mago:'assets/characters/mago/sheet.png',Arqueiro:'assets/characters/arqueiro/sheet.png',Ladino:'assets/characters/ladino/sheet.png'};
const sideSpritePaths={Guerreiro:'assets/side/guerreiro.png',Mago:'assets/side/mago.png',Arqueiro:'assets/side/arqueiro.png',Ladino:'assets/side/ladino.png'};
const classSpriteImages={},sideSpriteImages={};for(const[k,v]of Object.entries(classSpritePaths)){const i=new Image;i.decoding='async';i.src=v;classSpriteImages[k]=i}for(const[k,v]of Object.entries(sideSpritePaths)){const i=new Image;i.decoding='async';i.src=v;sideSpriteImages[k]=i}
const goblinPixel=new Image();goblinPixel.decoding='async';goblinPixel.src='https://opengameart.org/sites/default/files/spritesheet-goblin-32x32-alpha.png';
function sideCombatWorld(){return world==='camp'||world==='rift'}function sideGroundY(){return 430}
function ensureSideState(){if(!player)return;player.sideVy=Number.isFinite(player.sideVy)?player.sideVy:0;player.sideOnGround=player.sideOnGround!==false;player.sideCrouch=!!player.sideCrouch;player.sideMoveT=Number(player.sideMoveT||0);player.sideAttackT=Math.max(0,Number(player.sideAttackT||0));player.sideHurtT=Math.max(0,Number(player.sideHurtT||0))}
function sideJump(){if(!player||!sideCombatWorld()||dialog.style.display==='block')return;ensureSideState();if(player.sideOnGround){player.sideVy=-505;player.sideOnGround=false;player.sideCrouch=false;toastMsg('Salto')}}""",'sprite paths')
sub(r"function update\(dt\)\{tickSkillCooldowns\(dt\);.*?updateHud\(\)\}", """function update(dt){tickSkillCooldowns(dt);if(!player||dialog.style.display==='block')return;ensureSideState();player.sideAttackT=Math.max(0,player.sideAttackT-dt);player.sideHurtT=Math.max(0,player.sideHurtT-dt);if(sideCombatWorld()){const left=(keys.a||keys.arrowleft?1:0),right=(keys.d||keys.arrowright?1:0);let dx=right-left;if(Math.abs(moveVec.x)>.18)dx=moveVec.x;player.sideCrouch=!!(keys.s||keys.arrowdown||moveVec.y>.55)&&player.sideOnGround;if((keys.w||keys.arrowup||moveVec.y<-.68)&&player.sideOnGround&&!player._jumpLatch){sideJump();player._jumpLatch=true}if(!(keys.w||keys.arrowup||moveVec.y<-.68))player._jumpLatch=false;if(Math.abs(dx)>.05){const dir=dx<0?-1:1;player.facing={x:dir,y:0};const speed=player.speed*(player.sideCrouch?.46:1);player.x=Math.max(28,Math.min(mapForWorld().w-28,player.x+dx*speed*dt));player.sideMoveT+=dt*Math.abs(dx)}player.sideVy+=1450*dt;player.y+=player.sideVy*dt;const ground=sideGroundY();if(player.y>=ground){player.y=ground;player.sideVy=0;player.sideOnGround=true}else player.sideOnGround=false}else{let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0)+moveVec.x,dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0)+moveVec.y,l=Math.hypot(dx,dy);if(l>1){dx/=l;dy/=l}if(l>.05){tryMove(player.x+dx*player.speed*dt,player.y+dy*player.speed*dt);player.facing={x:dx,y:dy}}}player.mana=Math.min(player.maxMana,player.mana+dt*.45);player.stamina=Math.min(player.maxStamina,player.stamina+dt*8);if(world==='camp'||world==='cistern'||world==='road'||world==='quarry'||world==='garden'||world==='rift'){for(const p of projectiles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;for(const g of goblins)if(!g.dead&&p.life>0&&Math.hypot(p.x-g.x,p.y-g.y)<g.r+p.r+24){hitGoblin(g,p.damage);p.life=0}}projectiles=projectiles.filter(p=>p.life>0);goblins.forEach(g=>updateGoblin(g,dt));if(goblins.filter(g=>g.dead).length>=5&&mission===S.GOBLINS){} }saveTimer+=dt;if(saveTimer>4){saveTimer=0;save()}updateHud()}""",'update loop')
rep("function tryMove(nx,ny){const map=mapForWorld();player.x=Math.max(28,Math.min(map.w-28,nx));player.y=sideCombatWorld()?sideGroundY():Math.max(28,Math.min(map.h-28,ny))}", "function tryMove(nx,ny){const map=mapForWorld();player.x=Math.max(28,Math.min(map.w-28,nx));if(!sideCombatWorld())player.y=Math.max(28,Math.min(map.h-28,ny))}",'tryMove')
rep("function basicAttack(dx,dy){if(!player||(!dx&&!dy))return;if(sideCombatWorld()){dx=dx<0?-1:1;dy=0}else{", "function basicAttack(dx,dy){if(!player||(!dx&&!dy))return;if(sideCombatWorld()){ensureSideState();player.sideAttackT=.28;dx=dx<0?-1:1;dy=0}else{", 'attack anim')
rep("projectiles.push({x:player.x+dx*24,y:player.y+dy*24,vx:dx*430,vy:dy*430,r:6,life:1.2,damage:player.class==='Mago'?12:10})", "projectiles.push({x:player.x+dx*24,y:player.y+(sideCombatWorld()?-58:dy*24),vx:dx*430,vy:sideCombatWorld()?0:dy*430,r:6,life:1.2,damage:player.class==='Mago'?12:10})", 'projectile height')
rep("function hurtPlayer(d){if(player&&player.guardUntil>Date.now())d*=.35;", "function hurtPlayer(d){if(player&&sideCombatWorld()){ensureSideState();player.sideHurtT=.30}if(player&&player.guardUntil>Date.now())d*=.35;", 'hurt anim')
sub(r"function updateGoblin\(g,dt\)\{if\(g\.dead\)return;if\(sideCombatWorld\(\)\)g\.y=sideGroundY\(\);g\.cooldown=.*?\}\nconst classSpritePaths=", """function updateGoblin(g,dt){if(g.dead)return;if(sideCombatWorld())g.y=sideGroundY();g.cooldown=Math.max(0,g.cooldown-dt);const dx=player.x-g.x,dy=player.y-g.y,d=sideCombatWorld()?Math.abs(dx):(Math.hypot(dx,dy)||1);if(g.state==='windup'){g.windup-=dt;if(g.windup<=0){const hit=sideCombatWorld()?Math.abs(player.x-g.attackX)<62:Math.hypot(player.x-g.attackX,player.y-g.attackY)<48;if(hit)hurtPlayer(12);g.state='recover';g.cooldown=.75;g.windup=.28}return}if(g.state==='recover'){g.windup-=dt;if(g.windup<=0)g.state='idle';return}if(d<72&&g.cooldown<=0){g.state='windup';g.windup=.62;g.attackX=player.x;g.attackY=player.y;return}if(d<260&&d>60){const nx=g.x+(dx<0?-1:1)*58*dt,ny=sideCombatWorld()?sideGroundY():g.y+dy/(d||1)*58*dt;if(!(mapForWorld().obstacles||[]).some(o=>circleRectHit(nx,ny,g.r,o))){g.x=nx;g.y=ny}}}
const classSpritePaths=""",'goblin update')
sub(r"function drawPlayer\(\)\{.*?\}\nfunction drawAim", """function drawPlayer(){ensureSideState();if(sideCombatWorld()){const img=sideSpriteImages[player.class];let frame=0;if(player.sideHurtT>0)frame=8;else if(player.sideAttackT>0)frame=player.sideAttackT>.13?6:7;else if(!player.sideOnGround)frame=2;else if(player.sideCrouch)frame=9;else if(Math.abs((keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0)+moveVec.x)>.05)frame=1+(Math.floor(player.sideMoveT*9)%5);const row=(player.facing.x||1)<0?1:0,dw=player.sideCrouch?108:124,dh=player.sideCrouch?86:124,dy=player.y-dh+8;if(img&&img.complete&&img.naturalWidth){ctx.imageSmoothingEnabled=false;ctx.drawImage(img,frame*64,row*64,64,64,player.x-dw/2,dy,dw,dh)}else{ctx.fillStyle='#9aa4b5';ctx.fillRect(player.x-16,player.y-64,32,64)}label(player.name,player.x-34,dy-10,'#f5ead2',12)}else{const img=classSpriteImages[player.class];let frame=0;if(player.facing){const x=player.facing.x||0,y=player.facing.y||0;if(Math.abs(x)>.65&&Math.abs(y)<.45)frame=x>0?2:6;else if(y<-.45)frame=x>.35?3:x<-.35?5:4;else if(y>.45)frame=x>.35?1:x<-.35?7:0}if(img&&img.complete&&img.naturalWidth){ctx.imageSmoothingEnabled=false;ctx.drawImage(img,frame*96,0,96,96,player.x-48,player.y-74,96,96)}else{ctx.fillStyle='#9aa4b5';ctx.fillRect(player.x-16,player.y-35,32,35)}label(player.name,player.x-30,player.y-80,'#f5ead2',12)}for(const p of projectiles){ctx.fillStyle=player.class==='Mago'?'#65a8ff':'#f0d58b';ctx.beginPath();ctx.arc(p.x,p.y,p.r+2,0,Math.PI*2);ctx.fill()}}
function drawAim""",'drawPlayer')
sub(r"function drawCamp\(\)\{.*?\}\nfunction drawPlayer", """function drawCamp(){const g=ctx.createLinearGradient(0,0,0,540);g.addColorStop(0,'#101827');g.addColorStop(.55,'#1d2530');g.addColorStop(1,'#120f12');ctx.fillStyle=g;ctx.fillRect(0,0,camp.w,camp.h);ctx.fillStyle='#0c111a';for(let x=0;x<camp.w;x+=250){ctx.fillRect(x,190,185,260);ctx.fillStyle='#253145';ctx.fillRect(x+28,248,20,88);ctx.fillRect(x+93,220,18,112);ctx.fillStyle='#0c111a'}ctx.fillStyle='#27211d';ctx.fillRect(0,455,camp.w,85);ctx.fillStyle='#3d3228';for(let x=0;x<camp.w;x+=64)ctx.fillRect(x,455+(x%3)*3,50,5);ctx.strokeStyle='#d94658';ctx.lineWidth=8;ctx.shadowColor='#ff3b55';ctx.shadowBlur=20;ctx.beginPath();ctx.ellipse(280,345,55,90,0,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0;ctx.lineWidth=1;const t=performance.now()/1000;for(const m of goblins){if(m.dead)continue;if(m.state==='windup'){ctx.fillStyle='#ff384433';ctx.beginPath();ctx.ellipse(m.attackX,sideGroundY()+8,54,18,0,0,Math.PI*2);ctx.fill()}if(goblinPixel.complete&&goblinPixel.naturalWidth){const f=m.state==='windup'?0:Math.floor(t*8+m.id)%8;ctx.imageSmoothingEnabled=false;ctx.save();if(m.x>player.x){ctx.translate(m.x,0);ctx.scale(-1,1);ctx.drawImage(goblinPixel,f*32,0,32,32,-45,m.y-86,90,90)}else ctx.drawImage(goblinPixel,f*32,0,32,32,m.x-45,m.y-86,90,90);ctx.restore()}else{ctx.fillStyle='#688947';ctx.fillRect(m.x-14,m.y-60,28,28);ctx.fillStyle='#27301f';ctx.fillRect(m.x-12,m.y-32,24,32)}ctx.fillStyle='#222';ctx.fillRect(m.x-27,m.y+5,54,5);ctx.fillStyle='#c94a4d';ctx.fillRect(m.x-27,m.y+5,54*m.hp/m.maxHp,5);label('Goblin',m.x-25,m.y-92,'#d7efc4',11)}if(goblins.filter(x=>x.dead).length>=5){portal(camp.returnPortal.x,camp.returnPortal.y-35);label('Retorno à cidade',camp.returnPortal.x-58,camp.returnPortal.y-100,'#e8d7ff',12)}}
function drawPlayer""",'drawCamp')
rep("sceneLayer.style.backgroundImage=`url('${world==='guild'?'assets/scenes/guild.svg':'assets/scenes/city.svg'}')`", "sceneLayer.style.backgroundImage=`url('${world==='guild'?'assets/scenes/guild.webp':'assets/scenes/city.webp'}')`", 'scene backgrounds')
rep("combatHotbar.style.display=sideCombatWorld()?'flex':'none';", "combatHotbar.style.display=sideCombatWorld()?'flex':'none';document.getElementById('sideControlHint').style.display=sideCombatWorld()?'block':'none';", 'hint visibility')
sub(r"document\.querySelectorAll\('\[data-vmenu\]'\).*?addEventListener\('keyup',e=>keys\[e\.key\.toLowerCase\(\)\]=false\);", """function handleVMenu(a){if(!player)return;if(a==='skills')showSkillsPanel();else if(a==='base'){if(world==='base')showBasePanel();else if(world==='city')enterBase();else toastMsg('A Base é acessada pela cidade.')}else if(a==='missions')showDynamicBoard();else if(a==='guild'){if(world==='city')enterGuild();else if(world==='guild')talkHelena();else toastMsg('Retorne a Esperança para acessar a Guilda.')}else if(a==='character')showSimplePanel('Personagem',`${player.name}<br>${player.class} • Nível ${player.level||1}<br>EXP ${player.xp||0}<br>Rank ${player.guildCard?'F':'Sem registro'}`);else if(a==='inventory')showSimplePanel('Inventário',Object.entries(ensureInventory()).map(([k,v])=>`${k}: ${v}`).join('<br>')||'Inventário vazio.');else if(a==='map')showSimplePanel('Mapa',`Local atual: ${world==='guild'?'Guilda':world==='city'?'Esperança':'Área de missão'}<br>Portais e regiões serão liberados pela progressão.`);else showSimplePanel('Configurações','Interface v0.9.1 • exploração narrativa + combate lateral.');renderNarrativeScene()}
function handleCombatAction(a){if(!player)return;if(a==='q'||a==='e'||a==='r')useSkill(a);else if(a==='interact')interact();else basicAttack(player.facing.x||1,0)}
document.querySelectorAll('[data-vmenu]').forEach(b=>{b.type='button';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(b.dataset.v091Pointer==='1'){delete b.dataset.v091Pointer;return}handleVMenu(b.dataset.vmenu)})});document.querySelectorAll('[data-combat]').forEach(b=>{b.type='button';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(b.dataset.v091Pointer==='1'){delete b.dataset.v091Pointer;return}handleCombatAction(b.dataset.combat)})});document.addEventListener('pointerup',e=>{const vm=e.target.closest?.('[data-vmenu]');if(vm&&!vm.dataset.v091Pointer){vm.dataset.v091Pointer='1';setTimeout(()=>delete vm.dataset.v091Pointer,400);handleVMenu(vm.dataset.vmenu);return}const cb=e.target.closest?.('[data-combat]');if(cb&&!cb.dataset.v091Pointer){cb.dataset.v091Pointer='1';setTimeout(()=>delete cb.dataset.v091Pointer,400);handleCombatAction(cb.dataset.combat)}});document.querySelectorAll('.choice.cls').forEach(el=>{const art=document.createElement('div');art.className='class-art';art.style.backgroundImage=`url('${classSpritePaths[el.dataset.class]}')`;el.prepend(art)});addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(sideCombatWorld()&&(e.code==='KeyW'||e.code==='ArrowUp')&&!e.repeat)sideJump();if(e.code==='KeyQ')useSkill('q');else if(e.code==='KeyE'){if(sideCombatWorld())useSkill('e');else if(currentInteract()&&!e.shiftKey)interact();else useSkill('e')}else if(e.code==='KeyR')useSkill('r');else if(e.code==='KeyF')interact();else if(e.code==='Space'&&sideCombatWorld())sideJump()},{passive:false});addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=false;if(e.code==='KeyW'||e.code==='ArrowUp')player&&(player._jumpLatch=false)});""",'input/menu handlers')
rep("function enterCamp(){world='camp';mission=S.GOBLINS;camp.w=2050;camp.h=540;camp.returnPortal={x:1940,y:410,r:36};camp.obstacles=[];player.x=150;player.y=430;player.facing={x:1,y:0};player.hp=player.maxHp;", "function enterCamp(){world='camp';mission=S.GOBLINS;camp.w=2050;camp.h=540;camp.returnPortal={x:1940,y:410,r:36};camp.obstacles=[];player.x=150;player.y=430;player.facing={x:1,y:0};player.sideVy=0;player.sideOnGround=true;player.sideCrouch=false;player.hp=player.maxHp;", 'enter camp side init')
s=s.replace("world='rift';player.x=150;player.y=690;", "world='rift';player.x=150;player.y=430;player.sideVy=0;player.sideOnGround=true;player.sideCrouch=false;")
s=s.replace('</body>','<!-- v0.9.1 real-art pass: OpenGameArt CC0 Goblin Monster by ImogiaGames (runtime remote sprite). -->\n</body>')
for q in ['v0.9.1','assets/scenes/city.webp','assets/characters/guerreiro/sheet.png','assets/side/guerreiro.png','function sideJump','function handleVMenu','A / D mover','portrait-raul']:
    if q not in s: raise SystemExit('missing '+q)
p.write_text(s,encoding='utf-8')
print('v0.9.1 real-art patch aplicado',len(s))