(()=>{
const slides=[
 {cls:'ruins',k:'PRÓLOGO • ANO ZERO',t:'O mundo caiu',p:'As primeiras criaturas atravessaram fendas que ninguém sabia explicar. Cidades inteiras desapareceram em poucos dias. Exércitos falharam, fronteiras ruíram e os sobreviventes passaram a viver entre muralhas improvisadas, ruínas e zonas abandonadas.'},
 {cls:'portal',k:'PRÓLOGO • AS FENDAS',t:'Então vieram os Portais',p:'Alguns levavam a territórios hostis. Outros despejavam monstros sobre a Terra. Cada portal passou a ser tratado como uma incursão: entrar, sobreviver, compreender suas regras e voltar antes que a passagem mudasse.'},
 {cls:'portal',k:'PRÓLOGO • O SISTEMA',t:'A humanidade despertou',p:'No limite da extinção, uma pequena parcela das pessoas passou a enxergar o Sistema. Força, magia, sentidos e habilidades impossíveis surgiram. Guerreiro, Mago, Arqueiro e Ladino tornaram-se as primeiras raízes conhecidas dos Despertos.'},
 {cls:'city',k:'PRÓLOGO • RECONSTRUÇÃO',t:'Guildas nasceram entre as ruínas',p:'Os Despertos passaram a proteger refúgios, explorar portais e recuperar território. As Guildas registram missões, ranques e incursões. Todo novato começa no Rank F. Antes de qualquer glória, é preciso provar que consegue voltar vivo.'},
 {cls:'orla',k:'ARCO I • ENTRE VÉUS',t:'O peso dos nomes',p:'Mas os monstros não são o único perigo. Na região de Orla, uma rua desapareceu dos mapas sem desaparecer da memória de todos. Algo dentro das Dobras está aprendendo a apagar pessoas, lugares e registros. Sua primeira grande campanha começa quando duas versões da mesma rua passam a existir ao mesmo tempo.'}
];
const chapters=[
 ['01','A rua que bebeu o próprio nome','Orla e a Cisterna'],['02','O pedágio dos ausentes','Estrada das Lanternas'],['03','O turno que não acabou','Pedreiras de Âmbar'],['04','As raízes que assinam','Jardim Suspenso'],['05','A margem do arquivo','Arquivo de Vidro'],['06','O navio que chegou tarde','Mar de Baixo'],['07','A segunda manhã','Namar Devolvida'],['08','Quem pode testemunhar','Tribunal das Ausências'],['09','Calor sem esquecimento','Forja do Inverno'],['10','As seis portas','Cerco das Seis Rotas'],['11','A conta do regente','Meridiano'],['12','O peso dos nomes','Pacto Final']
];
const q1=[
 ['mq_01','Filtros antes de glória','Entregue os filtros no abrigo da cisterna.'],
 ['mq_02','Quem ficou na água','Use as cordas para retirar três moradores.'],
 ['mq_03','Uma placa, duas ruas','Compare a placa molhada com o mapa de Inês.'],
 ['mq_04','O fundo responde','Desfaça o padrão que prende a cisterna e enfrente o Síndico da Cisterna.']
];
const css=document.createElement('link');css.rel='stylesheet';css.href='story-v0.7.css';document.head.appendChild(css);
const wrap=document.getElementById('wrap');if(!wrap)return;
const badge=document.createElement('div');badge.className='story-title-badge';badge.textContent='CAMPANHA • ENTRE VÉUS';wrap.appendChild(badge);
const btn=document.createElement('button');btn.id='storyBtn';btn.textContent='📖 HISTÓRIA';wrap.appendChild(btn);
const ov=document.createElement('div');ov.className='story-overlay';ov.innerHTML='<div class="story-card"><button class="story-close" aria-label="Fechar">×</button><div id="storyMount"></div></div>';wrap.appendChild(ov);
const mount=ov.querySelector('#storyMount');const close=()=>ov.classList.remove('open');ov.querySelector('.story-close').onclick=close;ov.addEventListener('click',e=>{if(e.target===ov)close()});
let introI=0;
function openIntro(fromMenu=false){introI=0;ov.dataset.mode=fromMenu?'intro-menu':'intro-new';renderIntro();ov.classList.add('open')}
function renderIntro(){const s=slides[introI];mount.innerHTML=`<div class="story-hero ${s.cls}"><div class="story-hero-content"><div class="story-kicker">${s.k}</div><h2>${s.t}</h2><p>${s.p}</p><div class="story-dots">${slides.map((_,i)=>`<i class="story-dot ${i===introI?'on':''}"></i>`).join('')}</div></div></div><div class="story-body"><div class="story-actions"><button class="story-action" id="storyPrev" ${introI===0?'disabled':''}>Voltar</button><button class="story-action primary" id="storyNext">${introI===slides.length-1?'Continuar para criação':'Próximo'}</button></div></div>`;
 const p=mount.querySelector('#storyPrev'),n=mount.querySelector('#storyNext');p.onclick=()=>{if(introI>0){introI--;renderIntro()}};n.onclick=()=>{if(introI<slides.length-1){introI++;renderIntro();return}close();if(ov.dataset.mode==='intro-new'){document.getElementById('menuScreen').style.display='none';document.getElementById('createScreen').style.display='flex'}}
}
function readSave(){try{return JSON.parse(localStorage.getItem('despertar-v070-save')||'null')}catch{return null}}
function tutorialDone(){const s=readSave();return !!(s&&s.mission==='done')}
function openChapters(){const unlocked=tutorialDone();mount.innerHTML=`<div class="story-hero orla"><div class="story-hero-content"><div class="story-kicker">DESPERTAR • CAMPANHA PRINCIPAL</div><h2>Entre Véus — O peso dos nomes</h2><p>Doze capítulos foram adaptados para o mundo de Despertar. A invasão, os Portais, as Guildas e o Sistema continuam sendo a base do jogo. Entre Véus entra como a primeira grande campanha narrativa dentro desse mundo.</p></div></div><div class="story-body"><div class="lore-box"><b>Prólogo operacional</b><br>Seu registro Rank F e a incursão contra os Goblins continuam exatamente como tutorial do jogo. Depois disso, a campanha de Orla começa. Nenhuma mecânica de movimentação ou classe foi substituída.</div><div class="chapter-list" style="margin-top:14px">${chapters.map((c,i)=>`<div class="chapter ${i===0?'unlocked':'locked'}" data-i="${i}"><small>CAPÍTULO ${c[0]} ${i===0?'• PRIMEIRO ARCO':'• BLOQUEADO'}</small><b>${c[1]}</b><span>${c[2]}</span></div>`).join('')}</div><div id="chapterDetail" class="chapter-detail"></div><div class="story-note">A campanha completa do ZIP foi mantida como estrutura narrativa. Nesta build de teste, o Capítulo 1 está apresentado na interface e os demais capítulos ficam visíveis como progressão futura.</div></div>`;
 mount.querySelectorAll('.chapter').forEach(el=>el.onclick=()=>showChapter(+el.dataset.i,unlocked));showChapter(0,unlocked);ov.classList.add('open')
}
function showChapter(i,unlocked){const d=mount.querySelector('#chapterDetail');if(!d)return;const c=chapters[i];if(i!==0){d.innerHTML=`<div class="lore-box"><b>Capítulo ${c[0]} — ${c[1]}</b><br>${c[2]}<br><br>Este capítulo já faz parte do arco narrativo importado e será conectado às missões jogáveis conforme avançarmos a implementação.</div>`;return}
 d.innerHTML=`<h3>Capítulo 01 — ${c[1]}</h3><div class="story-npc"><div class="story-portrait" style="background-image:url('assets/pixellab/ines-lume.png');background-size:cover;background-position:center">🗺</div><div><b>Inês Lume</b><div class="story-tag">Cartógrafa e mentora</div><div class="story-note">“Olhe para a borda do mapa. É onde eu costumava esconder meus erros.”</div></div></div><div class="story-npc"><div class="story-portrait" style="background-image:url('assets/pixellab/saira-vento.png');background-size:cover;background-position:center">⚔</div><div><b>Saira Vento</b><div class="story-tag">Capitã de resgate</div><div class="story-note">“Conte as pessoas antes das caixas. Depois conte de novo.”</div></div></div><div class="lore-box">Você chega a Orla trazendo filtros para uma cisterna. Uma mulher reconhece uma casa que todos juram nunca ter existido. Quando uma placa de rua se desfaz na água, você percebe que consegue lembrar duas versões do mesmo lugar. É o primeiro sinal de que as Dobras não estão apenas trazendo monstros: elas estão alterando a memória e os registros do mundo.</div>${q1.map(q=>`<div class="quest-row"><b>${q[0]} • ${q[1]}</b><span>${q[2]}</span></div>`).join('')}<div class="quest-row"><b>BOSS • Síndico da Cisterna</b><span>Válvulas, cerâmica e ordens de manutenção transformadas em criatura. Seus ataques são anunciados no chão antes do impacto.</span></div><div class="story-actions"><button class="story-action" id="previewScene">Ver cena de abertura</button><button class="story-action primary" ${unlocked?'':'disabled'}>${unlocked?'Campanha liberada':'Conclua o tutorial Rank F primeiro'}</button></div>`;
 const pv=d.querySelector('#previewScene');if(pv)pv.onclick=previewChapterOne
}
function previewChapterOne(){mount.innerHTML=`<div class="story-hero orla"><div class="story-hero-content"><div class="story-kicker">CAPÍTULO 01 • ORLA</div><h2>A rua que bebeu o próprio nome</h2><p>A chuva parou, mas a água na cisterna continua subindo. No mapa de Inês, a rua termina antes da praça. Na memória de uma moradora, existe uma casa depois dela. Você consegue lembrar das duas coisas ao mesmo tempo.</p></div></div><div class="story-body"><div class="story-npc"><div class="story-portrait">🗺</div><div><b>Inês Lume</b><div class="story-note">“Não tente decidir agora qual lembrança é a verdadeira. Primeiro tire as pessoas da água.”</div></div></div><div class="story-npc"><div class="story-portrait">⚔</div><div><b>Saira Vento</b><div class="story-note">“Três moradores ainda estão lá embaixo. Cordas primeiro. Perguntas depois.”</div></div></div><div class="story-actions"><button class="story-action primary" id="backChapters">Voltar aos capítulos</button></div></div>`;mount.querySelector('#backChapters').onclick=openChapters}
btn.onclick=openChapters;
const nb=document.getElementById('newBtn');if(nb)nb.onclick=()=>openIntro(false);
const menu=document.getElementById('menuScreen');if(menu){const p=menu.querySelector('.panel .row');if(p){const lore=document.createElement('button');lore.className='btn';lore.textContent='Prólogo';lore.onclick=()=>openIntro(true);p.appendChild(lore)}}
})();